version: '3'

tasks:
  # run server
  run:
    cmds:
      - doppler run -- go run cmd/*.go

  build:
    cmds:
      - docker build -f cmd/Dockerfile --platform linux/amd64 -t namhq1989/ezfeedback-api-server:latest -t namhq1989/ezfeedback-api-server:$(git rev-parse --short HEAD) .
      - docker push namhq1989/ezfeedback-api-server:latest
      - docker push namhq1989/ezfeedback-api-server:$(git rev-parse --short HEAD)

  # mandatory tools for code generation
  install-tools:
    cmds:
      - echo "installing tools"
      - go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - go install google.golang.org/protobuf/cmd/protoc-gen-go
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - go install github.com/jackc/tern/v2@latest
      - echo "done"

  # code generation
  code-gen:
    cmds:
      - echo "running code generation"
      - rm -rf internal/genproto
      - go generate ./...
      - echo "done"

  # database migration
  db-migrate:
    cmds:
      - doppler run -- sh -c "TERN_CONFIG=internal/database/migration/tern.conf TERN_MIGRATIONS=internal/database/migration tern migrate"

  # database generation
  db-gen:
    cmds:
      - rm -rf internal/database/gen
      - doppler run -- go run internal/database/generator/*.go

  # mock generation
  mock-gen:
    cmds:
      - rm -rf internal/mock

      # iam
      - mockgen -source=pkg/iam/domain/user.go -destination=internal/mock/iam/user.go -package=mockiam
      - mockgen -source=pkg/iam/domain/verification_code.go -destination=internal/mock/iam/verification_code.go -package=mockiam
      - mockgen -source=pkg/iam/domain/queue.go -destination=internal/mock/iam/queue.go -package=mockiam
      - mockgen -source=pkg/iam/domain/jwt.go -destination=internal/mock/iam/jwt.go -package=mockiam
      - mockgen -source=pkg/iam/domain/mailer.go -destination=internal/mock/iam/mailer.go -package=mockiam
      - mockgen -source=pkg/iam/domain/caching.go -destination=internal/mock/iam/caching.go -package=mockiam
      - mockgen -source=pkg/iam/domain/service.go -destination=internal/mock/iam/service.go -package=mockiam

      # project
      - mockgen -source=pkg/project/domain/project.go -destination=internal/mock/project/project.go -package=mockproject
      - mockgen -source=pkg/project/domain/project_setting.go -destination=internal/mock/project/project_setting.go -package=mockproject
      - mockgen -source=pkg/project/domain/project_category.go -destination=internal/mock/project/project_category.go -package=mockproject
      - mockgen -source=pkg/project/domain/project_campaign.go -destination=internal/mock/project/project_campaign.go -package=mockproject
      - mockgen -source=pkg/project/domain/project_campaign_category.go -destination=internal/mock/project/project_campaign_category.go -package=mockproject
      - mockgen -source=pkg/project/domain/project_collaborator.go -destination=internal/mock/project/project_collaborator.go -package=mockproject
      - mockgen -source=pkg/project/domain/caching.go -destination=internal/mock/project/caching.go -package=mockproject
      - mockgen -source=pkg/project/domain/billing.go -destination=internal/mock/project/billing.go -package=mockproject
      - mockgen -source=pkg/project/domain/iam.go -destination=internal/mock/project/iam.go -package=mockproject
      - mockgen -source=pkg/project/domain/service.go -destination=internal/mock/project/service.go -package=mockproject

      # feedback
      - mockgen -source=pkg/feedback/domain/feedback.go -destination=internal/mock/feedback/feedback.go -package=mockfeedback
      - mockgen -source=pkg/feedback/domain/feedback_reply.go -destination=internal/mock/feedback/feedback_reply.go -package=mockfeedback
      - mockgen -source=pkg/feedback/domain/queue.go -destination=internal/mock/feedback/queue.go -package=mockfeedback
      - mockgen -source=pkg/feedback/domain/caching.go -destination=internal/mock/feedback/caching.go -package=mockfeedback
      - mockgen -source=pkg/feedback/domain/externalapi.go -destination=internal/mock/feedback/externalapi.go -package=mockfeedback
      - mockgen -source=pkg/feedback/domain/billing.go -destination=internal/mock/feedback/billing.go -package=mockfeedback
      - mockgen -source=pkg/feedback/domain/project.go -destination=internal/mock/feedback/project.go -package=mockfeedback
      - mockgen -source=pkg/feedback/domain/notification.go -destination=internal/mock/feedback/notification.go -package=mockfeedback
      - mockgen -source=pkg/feedback/domain/iam.go -destination=internal/mock/feedback/iam.go -package=mockfeedback
      - mockgen -source=pkg/feedback/domain/service.go -destination=internal/mock/feedback/service.go -package=mockfeedback

      # notification
      - mockgen -source=pkg/notification/domain/notification.go -destination=internal/mock/notification/notification.go -package=mocknotification
      - mockgen -source=pkg/notification/domain/notification_reminder.go -destination=internal/mock/notification/notification_reminder.go -package=mocknotification
      - mockgen -source=pkg/notification/domain/user_project_notification_setting.go -destination=internal/mock/notification/user_project_notification_setting.go -package=mocknotification
      - mockgen -source=pkg/notification/domain/caching.go -destination=internal/mock/notification/caching.go -package=mocknotification
      - mockgen -source=pkg/notification/domain/queue.go -destination=internal/mock/notification/queue.go -package=mocknotification
      - mockgen -source=pkg/notification/domain/mailer.go -destination=internal/mock/notification/mailer.go -package=mocknotification
      - mockgen -source=pkg/notification/domain/feedback.go -destination=internal/mock/notification/feedback.go -package=mocknotification
      - mockgen -source=pkg/notification/domain/iam.go -destination=internal/mock/notification/iam..go -package=mocknotification
      - mockgen -source=pkg/notification/domain/project.go -destination=internal/mock/notification/project.go -package=mocknotification
      - mockgen -source=pkg/notification/domain/service.go -destination=internal/mock/notification/service.go -package=mocknotification

  # swagger generation
  swagger-gen:
    swag init --parseDependencyLevel 1 -g cmd/main.go \
    -o ./docs

  # test
  test:
    cmds:
      - gotestsum --junitfile-hide-empty-pkg --format testname ./pkg/...
