// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/notification/domain/caching.go
//
// Generated by this command:
//
//	mockgen -source=pkg/notification/domain/caching.go -destination=internal/mock/notification/caching.go -package=mocknotification
//

// Package mocknotification is a generated GoMock package.
package mocknotification

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/notification/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockCachingRepository is a mock of CachingRepository interface.
type MockCachingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCachingRepositoryMockRecorder
	isgomock struct{}
}

// MockCachingRepositoryMockRecorder is the mock recorder for MockCachingRepository.
type MockCachingRepositoryMockRecorder struct {
	mock *MockCachingRepository
}

// NewMockCachingRepository creates a new mock instance.
func NewMockCachingRepository(ctrl *gomock.Controller) *MockCachingRepository {
	mock := &MockCachingRepository{ctrl: ctrl}
	mock.recorder = &MockCachingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCachingRepository) EXPECT() *MockCachingRepositoryMockRecorder {
	return m.recorder
}

// DeleteProjectByID mocks base method.
func (m *MockCachingRepository) DeleteProjectByID(ctx *appcontext.AppContext, userID, projectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectByID", ctx, userID, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectByID indicates an expected call of DeleteProjectByID.
func (mr *MockCachingRepositoryMockRecorder) DeleteProjectByID(ctx, userID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectByID", reflect.TypeOf((*MockCachingRepository)(nil).DeleteProjectByID), ctx, userID, projectID)
}

// GetUserProjectNotificationSetting mocks base method.
func (m *MockCachingRepository) GetUserProjectNotificationSetting(ctx *appcontext.AppContext, userID, projectID string) (*domain.UserProjectNotificationSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProjectNotificationSetting", ctx, userID, projectID)
	ret0, _ := ret[0].(*domain.UserProjectNotificationSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProjectNotificationSetting indicates an expected call of GetUserProjectNotificationSetting.
func (mr *MockCachingRepositoryMockRecorder) GetUserProjectNotificationSetting(ctx, userID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProjectNotificationSetting", reflect.TypeOf((*MockCachingRepository)(nil).GetUserProjectNotificationSetting), ctx, userID, projectID)
}

// SetUserProjectNotificationSetting mocks base method.
func (m *MockCachingRepository) SetUserProjectNotificationSetting(ctx *appcontext.AppContext, userID, projectID string, setting domain.UserProjectNotificationSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserProjectNotificationSetting", ctx, userID, projectID, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserProjectNotificationSetting indicates an expected call of SetUserProjectNotificationSetting.
func (mr *MockCachingRepositoryMockRecorder) SetUserProjectNotificationSetting(ctx, userID, projectID, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserProjectNotificationSetting", reflect.TypeOf((*MockCachingRepository)(nil).SetUserProjectNotificationSetting), ctx, userID, projectID, setting)
}
