// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/notification/domain/feedback.go
//
// Generated by this command:
//
//	mockgen -source=pkg/notification/domain/feedback.go -destination=internal/mock/notification/feedback.go -package=mocknotification
//

// Package mocknotification is a generated GoMock package.
package mocknotification

import (
	reflect "reflect"
	time "time"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/notification/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedbackHub is a mock of FeedbackHub interface.
type MockFeedbackHub struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackHubMockRecorder
}

// MockFeedbackHubMockRecorder is the mock recorder for MockFeedbackHub.
type MockFeedbackHubMockRecorder struct {
	mock *MockFeedbackHub
}

// NewMockFeedbackHub creates a new mock instance.
func NewMockFeedbackHub(ctrl *gomock.Controller) *MockFeedbackHub {
	mock := &MockFeedbackHub{ctrl: ctrl}
	mock.recorder = &MockFeedbackHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackHub) EXPECT() *MockFeedbackHubMockRecorder {
	return m.recorder
}

// GetProjectStatsForNotificationReminder mocks base method.
func (m *MockFeedbackHub) GetProjectStatsForNotificationReminder(ctx *appcontext.AppContext, projectID string, timestamp time.Time, limit int64) (int64, []domain.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectStatsForNotificationReminder", ctx, projectID, timestamp, limit)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]domain.Feedback)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetProjectStatsForNotificationReminder indicates an expected call of GetProjectStatsForNotificationReminder.
func (mr *MockFeedbackHubMockRecorder) GetProjectStatsForNotificationReminder(ctx, projectID, timestamp, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectStatsForNotificationReminder", reflect.TypeOf((*MockFeedbackHub)(nil).GetProjectStatsForNotificationReminder), ctx, projectID, timestamp, limit)
}
