// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/notification/domain/iam.go
//
// Generated by this command:
//
//	mockgen -source=pkg/notification/domain/iam.go -destination=internal/mock/notification/iam..go -package=mocknotification
//

// Package mocknotification is a generated GoMock package.
package mocknotification

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/notification/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockIAMHub is a mock of IAMHub interface.
type MockIAMHub struct {
	ctrl     *gomock.Controller
	recorder *MockIAMHubMockRecorder
	isgomock struct{}
}

// MockIAMHubMockRecorder is the mock recorder for MockIAMHub.
type MockIAMHubMockRecorder struct {
	mock *MockIAMHub
}

// NewMockIAMHub creates a new mock instance.
func NewMockIAMHub(ctrl *gomock.Controller) *MockIAMHub {
	mock := &MockIAMHub{ctrl: ctrl}
	mock.recorder = &MockIAMHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAMHub) EXPECT() *MockIAMHubMockRecorder {
	return m.recorder
}

// GetUsersByIDs mocks base method.
func (m *MockIAMHub) GetUsersByIDs(ctx *appcontext.AppContext, userIDs []string) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByIDs", ctx, userIDs)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByIDs indicates an expected call of GetUsersByIDs.
func (mr *MockIAMHubMockRecorder) GetUsersByIDs(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByIDs", reflect.TypeOf((*MockIAMHub)(nil).GetUsersByIDs), ctx, userIDs)
}
