// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/notification/domain/mailer.go
//
// Generated by this command:
//
//	mockgen -source=pkg/notification/domain/mailer.go -destination=internal/mock/notification/mailer.go -package=mocknotification
//

// Package mocknotification is a generated GoMock package.
package mocknotification

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/notification/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockMailerRepository is a mock of MailerRepository interface.
type MockMailerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMailerRepositoryMockRecorder
}

// MockMailerRepositoryMockRecorder is the mock recorder for MockMailerRepository.
type MockMailerRepositoryMockRecorder struct {
	mock *MockMailerRepository
}

// NewMockMailerRepository creates a new mock instance.
func NewMockMailerRepository(ctrl *gomock.Controller) *MockMailerRepository {
	mock := &MockMailerRepository{ctrl: ctrl}
	mock.recorder = &MockMailerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailerRepository) EXPECT() *MockMailerRepositoryMockRecorder {
	return m.recorder
}

// SendNewFeedbackEmail mocks base method.
func (m *MockMailerRepository) SendNewFeedbackEmail(ctx *appcontext.AppContext, toEmail string, feedbacks []domain.Feedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNewFeedbackEmail", ctx, toEmail, feedbacks)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNewFeedbackEmail indicates an expected call of SendNewFeedbackEmail.
func (mr *MockMailerRepositoryMockRecorder) SendNewFeedbackEmail(ctx, toEmail, feedbacks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNewFeedbackEmail", reflect.TypeOf((*MockMailerRepository)(nil).SendNewFeedbackEmail), ctx, toEmail, feedbacks)
}
