// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/notification/domain/notification.go
//
// Generated by this command:
//
//	mockgen -source=pkg/notification/domain/notification.go -destination=internal/mock/notification/notification.go -package=mocknotification
//

// Package mocknotification is a generated GoMock package.
package mocknotification

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/notification/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// CleanupStale mocks base method.
func (m *MockNotificationRepository) CleanupStale(ctx *appcontext.AppContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupStale", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupStale indicates an expected call of CleanupStale.
func (mr *MockNotificationRepositoryMockRecorder) CleanupStale(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupStale", reflect.TypeOf((*MockNotificationRepository)(nil).CleanupStale), ctx)
}

// CountWithFilter mocks base method.
func (m *MockNotificationRepository) CountWithFilter(ctx *appcontext.AppContext, filter domain.NotificationFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountWithFilter", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountWithFilter indicates an expected call of CountWithFilter.
func (mr *MockNotificationRepositoryMockRecorder) CountWithFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountWithFilter", reflect.TypeOf((*MockNotificationRepository)(nil).CountWithFilter), ctx, filter)
}

// Create mocks base method.
func (m *MockNotificationRepository) Create(ctx *appcontext.AppContext, notification domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationRepositoryMockRecorder) Create(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationRepository)(nil).Create), ctx, notification)
}

// Delete mocks base method.
func (m *MockNotificationRepository) Delete(ctx *appcontext.AppContext, notification domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationRepositoryMockRecorder) Delete(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationRepository)(nil).Delete), ctx, notification)
}

// FindByID mocks base method.
func (m *MockNotificationRepository) FindByID(ctx *appcontext.AppContext, id string) (*domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockNotificationRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockNotificationRepository)(nil).FindByID), ctx, id)
}

// FindWithFilter mocks base method.
func (m *MockNotificationRepository) FindWithFilter(ctx *appcontext.AppContext, filter domain.NotificationFilter) ([]domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithFilter", ctx, filter)
	ret0, _ := ret[0].([]domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithFilter indicates an expected call of FindWithFilter.
func (mr *MockNotificationRepositoryMockRecorder) FindWithFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithFilter", reflect.TypeOf((*MockNotificationRepository)(nil).FindWithFilter), ctx, filter)
}

// GenerateNewFeedbackContent mocks base method.
func (m *MockNotificationRepository) GenerateNewFeedbackContent(arg0 *appcontext.AppContext, language, projectTitle string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateNewFeedbackContent", arg0, language, projectTitle)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateNewFeedbackContent indicates an expected call of GenerateNewFeedbackContent.
func (mr *MockNotificationRepositoryMockRecorder) GenerateNewFeedbackContent(arg0, language, projectTitle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateNewFeedbackContent", reflect.TypeOf((*MockNotificationRepository)(nil).GenerateNewFeedbackContent), arg0, language, projectTitle)
}

// Update mocks base method.
func (m *MockNotificationRepository) Update(ctx *appcontext.AppContext, notification domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockNotificationRepositoryMockRecorder) Update(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNotificationRepository)(nil).Update), ctx, notification)
}
