// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/notification/domain/notification_reminder.go
//
// Generated by this command:
//
//	mockgen -source=pkg/notification/domain/notification_reminder.go -destination=internal/mock/notification/notification_reminder.go -package=mocknotification
//

// Package mocknotification is a generated GoMock package.
package mocknotification

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/notification/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationReminderRepository is a mock of NotificationReminderRepository interface.
type MockNotificationReminderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationReminderRepositoryMockRecorder
}

// MockNotificationReminderRepositoryMockRecorder is the mock recorder for MockNotificationReminderRepository.
type MockNotificationReminderRepositoryMockRecorder struct {
	mock *MockNotificationReminderRepository
}

// NewMockNotificationReminderRepository creates a new mock instance.
func NewMockNotificationReminderRepository(ctrl *gomock.Controller) *MockNotificationReminderRepository {
	mock := &MockNotificationReminderRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationReminderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationReminderRepository) EXPECT() *MockNotificationReminderRepositoryMockRecorder {
	return m.recorder
}

// CleanupStale mocks base method.
func (m *MockNotificationReminderRepository) CleanupStale(ctx *appcontext.AppContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupStale", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupStale indicates an expected call of CleanupStale.
func (mr *MockNotificationReminderRepositoryMockRecorder) CleanupStale(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupStale", reflect.TypeOf((*MockNotificationReminderRepository)(nil).CleanupStale), ctx)
}

// Create mocks base method.
func (m *MockNotificationReminderRepository) Create(ctx *appcontext.AppContext, reminder domain.NotificationReminder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reminder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationReminderRepositoryMockRecorder) Create(ctx, reminder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationReminderRepository)(nil).Create), ctx, reminder)
}

// Delete mocks base method.
func (m *MockNotificationReminderRepository) Delete(ctx *appcontext.AppContext, reminder domain.NotificationReminder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, reminder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNotificationReminderRepositoryMockRecorder) Delete(ctx, reminder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNotificationReminderRepository)(nil).Delete), ctx, reminder)
}

// FindAllExisting mocks base method.
func (m *MockNotificationReminderRepository) FindAllExisting(ctx *appcontext.AppContext) ([]domain.NotificationReminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllExisting", ctx)
	ret0, _ := ret[0].([]domain.NotificationReminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllExisting indicates an expected call of FindAllExisting.
func (mr *MockNotificationReminderRepositoryMockRecorder) FindAllExisting(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllExisting", reflect.TypeOf((*MockNotificationReminderRepository)(nil).FindAllExisting), ctx)
}

// FindByProjectID mocks base method.
func (m *MockNotificationReminderRepository) FindByProjectID(ctx *appcontext.AppContext, projectID string) (*domain.NotificationReminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectID", ctx, projectID)
	ret0, _ := ret[0].(*domain.NotificationReminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectID indicates an expected call of FindByProjectID.
func (mr *MockNotificationReminderRepositoryMockRecorder) FindByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectID", reflect.TypeOf((*MockNotificationReminderRepository)(nil).FindByProjectID), ctx, projectID)
}
