// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/notification/domain/project.go
//
// Generated by this command:
//
//	mockgen -source=pkg/notification/domain/project.go -destination=internal/mock/notification/project.go -package=mocknotification
//

// Package mocknotification is a generated GoMock package.
package mocknotification

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/notification/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectHub is a mock of ProjectHub interface.
type MockProjectHub struct {
	ctrl     *gomock.Controller
	recorder *MockProjectHubMockRecorder
}

// MockProjectHubMockRecorder is the mock recorder for MockProjectHub.
type MockProjectHubMockRecorder struct {
	mock *MockProjectHub
}

// NewMockProjectHub creates a new mock instance.
func NewMockProjectHub(ctrl *gomock.Controller) *MockProjectHub {
	mock := &MockProjectHub{ctrl: ctrl}
	mock.recorder = &MockProjectHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectHub) EXPECT() *MockProjectHubMockRecorder {
	return m.recorder
}

// GetProjectByID mocks base method.
func (m *MockProjectHub) GetProjectByID(ctx *appcontext.AppContext, projectID string) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByID", ctx, projectID)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByID indicates an expected call of GetProjectByID.
func (mr *MockProjectHubMockRecorder) GetProjectByID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByID", reflect.TypeOf((*MockProjectHub)(nil).GetProjectByID), ctx, projectID)
}

// GetProjectCollaborators mocks base method.
func (m *MockProjectHub) GetProjectCollaborators(ctx *appcontext.AppContext, projectID string) ([]domain.ProjectCollaborator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectCollaborators", ctx, projectID)
	ret0, _ := ret[0].([]domain.ProjectCollaborator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectCollaborators indicates an expected call of GetProjectCollaborators.
func (mr *MockProjectHubMockRecorder) GetProjectCollaborators(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectCollaborators", reflect.TypeOf((*MockProjectHub)(nil).GetProjectCollaborators), ctx, projectID)
}
