// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/notification/domain/queue.go
//
// Generated by this command:
//
//	mockgen -source=pkg/notification/domain/queue.go -destination=internal/mock/notification/queue.go -package=mocknotification
//

// Package mocknotification is a generated GoMock package.
package mocknotification

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/notification/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueRepository is a mock of QueueRepository interface.
type MockQueueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueueRepositoryMockRecorder
}

// MockQueueRepositoryMockRecorder is the mock recorder for MockQueueRepository.
type MockQueueRepositoryMockRecorder struct {
	mock *MockQueueRepository
}

// NewMockQueueRepository creates a new mock instance.
func NewMockQueueRepository(ctrl *gomock.Controller) *MockQueueRepository {
	mock := &MockQueueRepository{ctrl: ctrl}
	mock.recorder = &MockQueueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueRepository) EXPECT() *MockQueueRepositoryMockRecorder {
	return m.recorder
}

// ProcessNotificationReminder mocks base method.
func (m *MockQueueRepository) ProcessNotificationReminder(ctx *appcontext.AppContext, payload domain.QueueProcessNotificationReminderPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessNotificationReminder", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessNotificationReminder indicates an expected call of ProcessNotificationReminder.
func (mr *MockQueueRepositoryMockRecorder) ProcessNotificationReminder(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessNotificationReminder", reflect.TypeOf((*MockQueueRepository)(nil).ProcessNotificationReminder), ctx, payload)
}
