// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/notification/domain/service.go
//
// Generated by this command:
//
//	mockgen -source=pkg/notification/domain/service.go -destination=internal/mock/notification/service.go -package=mocknotification
//

// Package mocknotification is a generated GoMock package.
package mocknotification

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/notification/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetUserProjectNotificationSetting mocks base method.
func (m *MockService) GetUserProjectNotificationSetting(ctx *appcontext.AppContext, userID, projectID string) (*domain.UserProjectNotificationSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProjectNotificationSetting", ctx, userID, projectID)
	ret0, _ := ret[0].(*domain.UserProjectNotificationSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProjectNotificationSetting indicates an expected call of GetUserProjectNotificationSetting.
func (mr *MockServiceMockRecorder) GetUserProjectNotificationSetting(ctx, userID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProjectNotificationSetting", reflect.TypeOf((*MockService)(nil).GetUserProjectNotificationSetting), ctx, userID, projectID)
}
