// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/notification/domain/user_project_notification_setting.go
//
// Generated by this command:
//
//	mockgen -source=pkg/notification/domain/user_project_notification_setting.go -destination=internal/mock/notification/user_project_notification_setting.go -package=mocknotification
//

// Package mocknotification is a generated GoMock package.
package mocknotification

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/notification/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockUserProjectNotificationSettingRepository is a mock of UserProjectNotificationSettingRepository interface.
type MockUserProjectNotificationSettingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserProjectNotificationSettingRepositoryMockRecorder
	isgomock struct{}
}

// MockUserProjectNotificationSettingRepositoryMockRecorder is the mock recorder for MockUserProjectNotificationSettingRepository.
type MockUserProjectNotificationSettingRepositoryMockRecorder struct {
	mock *MockUserProjectNotificationSettingRepository
}

// NewMockUserProjectNotificationSettingRepository creates a new mock instance.
func NewMockUserProjectNotificationSettingRepository(ctrl *gomock.Controller) *MockUserProjectNotificationSettingRepository {
	mock := &MockUserProjectNotificationSettingRepository{ctrl: ctrl}
	mock.recorder = &MockUserProjectNotificationSettingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProjectNotificationSettingRepository) EXPECT() *MockUserProjectNotificationSettingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserProjectNotificationSettingRepository) Create(ctx *appcontext.AppContext, setting domain.UserProjectNotificationSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserProjectNotificationSettingRepositoryMockRecorder) Create(ctx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserProjectNotificationSettingRepository)(nil).Create), ctx, setting)
}

// FindByUserIDAndProjectID mocks base method.
func (m *MockUserProjectNotificationSettingRepository) FindByUserIDAndProjectID(ctx *appcontext.AppContext, userID, projectID string) (*domain.UserProjectNotificationSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndProjectID", ctx, userID, projectID)
	ret0, _ := ret[0].(*domain.UserProjectNotificationSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndProjectID indicates an expected call of FindByUserIDAndProjectID.
func (mr *MockUserProjectNotificationSettingRepositoryMockRecorder) FindByUserIDAndProjectID(ctx, userID, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndProjectID", reflect.TypeOf((*MockUserProjectNotificationSettingRepository)(nil).FindByUserIDAndProjectID), ctx, userID, projectID)
}

// Update mocks base method.
func (m *MockUserProjectNotificationSettingRepository) Update(ctx *appcontext.AppContext, setting domain.UserProjectNotificationSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserProjectNotificationSettingRepositoryMockRecorder) Update(ctx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserProjectNotificationSettingRepository)(nil).Update), ctx, setting)
}
