syntax = "proto3";

package projectpb;

import "projectpb/message.proto";

service ProjectService {
  rpc GetProjectById(GetProjectByIdRequest) returns (GetProjectByIdResponse) {}
  rpc GetProjectCampaignById(GetProjectCampaignByIdRequest) returns (GetProjectCampaignByIdResponse) {}
  rpc GetProjectCollaborators(GetProjectCollaboratorsRequest) returns (GetProjectCollaboratorsResponse) {}
}

//
// GET PROJECT BY ID
//

message GetProjectByIdRequest {
  string traceId = 1;
  string projectId = 2;
}

message GetProjectByIdResponse {
  Project project = 1;
}

//
// GET PROJECT CAMPAIGN BY ID
//

message GetProjectCampaignByIdRequest {
  string traceId = 1;
  string campaignId = 2;
}

message GetProjectCampaignByIdResponse {
  ProjectCampaign campaign = 1;
  Project project = 2;
}

//
// GET PROJECT COLLABORATORS
//

message GetProjectCollaboratorsRequest {
  string traceId = 1;
  string projectId = 2;
}

message GetProjectCollaboratorsResponse {
  repeated ProjectCollaborator collaborators = 1;
}