// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/project/domain/billing.go
//
// Generated by this command:
//
//	mockgen -source=pkg/project/domain/billing.go -destination=internal/mock/project/billing.go -package=mockproject
//

// Package mockproject is a generated GoMock package.
package mockproject

import (
	reflect "reflect"

	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockBillingHub is a mock of BillingHub interface.
type MockBillingHub struct {
	ctrl     *gomock.Controller
	recorder *MockBillingHubMockRecorder
}

// MockBillingHubMockRecorder is the mock recorder for MockBillingHub.
type MockBillingHubMockRecorder struct {
	mock *MockBillingHub
}

// NewMockBillingHub creates a new mock instance.
func NewMockBillingHub(ctrl *gomock.Controller) *MockBillingHub {
	mock := &MockBillingHub{ctrl: ctrl}
	mock.recorder = &MockBillingHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingHub) EXPECT() *MockBillingHubMockRecorder {
	return m.recorder
}

// CanCreateProject mocks base method.
func (m *MockBillingHub) CanCreateProject(ctx *appcontext.AppContext, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanCreateProject", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanCreateProject indicates an expected call of CanCreateProject.
func (mr *MockBillingHubMockRecorder) CanCreateProject(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanCreateProject", reflect.TypeOf((*MockBillingHub)(nil).CanCreateProject), ctx, userID)
}
