// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/project/domain/caching.go
//
// Generated by this command:
//
//	mockgen -source=pkg/project/domain/caching.go -destination=internal/mock/project/caching.go -package=mockproject
//

// Package mockproject is a generated GoMock package.
package mockproject

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/project/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockCachingRepository is a mock of CachingRepository interface.
type MockCachingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCachingRepositoryMockRecorder
}

// MockCachingRepositoryMockRecorder is the mock recorder for MockCachingRepository.
type MockCachingRepositoryMockRecorder struct {
	mock *MockCachingRepository
}

// NewMockCachingRepository creates a new mock instance.
func NewMockCachingRepository(ctrl *gomock.Controller) *MockCachingRepository {
	mock := &MockCachingRepository{ctrl: ctrl}
	mock.recorder = &MockCachingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCachingRepository) EXPECT() *MockCachingRepositoryMockRecorder {
	return m.recorder
}

// DeleteApiGetProjectByID mocks base method.
func (m *MockCachingRepository) DeleteApiGetProjectByID(ctx *appcontext.AppContext, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApiGetProjectByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApiGetProjectByID indicates an expected call of DeleteApiGetProjectByID.
func (mr *MockCachingRepositoryMockRecorder) DeleteApiGetProjectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiGetProjectByID", reflect.TypeOf((*MockCachingRepository)(nil).DeleteApiGetProjectByID), ctx, id)
}

// DeleteApiGetProjectsByUserID mocks base method.
func (m *MockCachingRepository) DeleteApiGetProjectsByUserID(ctx *appcontext.AppContext, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteApiGetProjectsByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteApiGetProjectsByUserID indicates an expected call of DeleteApiGetProjectsByUserID.
func (mr *MockCachingRepositoryMockRecorder) DeleteApiGetProjectsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteApiGetProjectsByUserID", reflect.TypeOf((*MockCachingRepository)(nil).DeleteApiGetProjectsByUserID), ctx, userID)
}

// DeleteProjectByID mocks base method.
func (m *MockCachingRepository) DeleteProjectByID(ctx *appcontext.AppContext, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectByID indicates an expected call of DeleteProjectByID.
func (mr *MockCachingRepositoryMockRecorder) DeleteProjectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectByID", reflect.TypeOf((*MockCachingRepository)(nil).DeleteProjectByID), ctx, id)
}

// DeleteProjectCampaignsByProjectID mocks base method.
func (m *MockCachingRepository) DeleteProjectCampaignsByProjectID(ctx *appcontext.AppContext, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectCampaignsByProjectID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectCampaignsByProjectID indicates an expected call of DeleteProjectCampaignsByProjectID.
func (mr *MockCachingRepositoryMockRecorder) DeleteProjectCampaignsByProjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectCampaignsByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).DeleteProjectCampaignsByProjectID), ctx, id)
}

// DeleteProjectCategoriesByProjectID mocks base method.
func (m *MockCachingRepository) DeleteProjectCategoriesByProjectID(ctx *appcontext.AppContext, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectCategoriesByProjectID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectCategoriesByProjectID indicates an expected call of DeleteProjectCategoriesByProjectID.
func (mr *MockCachingRepositoryMockRecorder) DeleteProjectCategoriesByProjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectCategoriesByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).DeleteProjectCategoriesByProjectID), ctx, id)
}

// DeleteProjectCollaboratorsByProjectID mocks base method.
func (m *MockCachingRepository) DeleteProjectCollaboratorsByProjectID(ctx *appcontext.AppContext, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectCollaboratorsByProjectID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectCollaboratorsByProjectID indicates an expected call of DeleteProjectCollaboratorsByProjectID.
func (mr *MockCachingRepositoryMockRecorder) DeleteProjectCollaboratorsByProjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectCollaboratorsByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).DeleteProjectCollaboratorsByProjectID), ctx, id)
}

// DeleteProjectSettingByProjectID mocks base method.
func (m *MockCachingRepository) DeleteProjectSettingByProjectID(ctx *appcontext.AppContext, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectSettingByProjectID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectSettingByProjectID indicates an expected call of DeleteProjectSettingByProjectID.
func (mr *MockCachingRepositoryMockRecorder) DeleteProjectSettingByProjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectSettingByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).DeleteProjectSettingByProjectID), ctx, id)
}

// GetApiGetProjectByID mocks base method.
func (m *MockCachingRepository) GetApiGetProjectByID(ctx *appcontext.AppContext, id string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiGetProjectByID", ctx, id)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiGetProjectByID indicates an expected call of GetApiGetProjectByID.
func (mr *MockCachingRepositoryMockRecorder) GetApiGetProjectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiGetProjectByID", reflect.TypeOf((*MockCachingRepository)(nil).GetApiGetProjectByID), ctx, id)
}

// GetApiGetProjectsByUserID mocks base method.
func (m *MockCachingRepository) GetApiGetProjectsByUserID(ctx *appcontext.AppContext, userID string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiGetProjectsByUserID", ctx, userID)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiGetProjectsByUserID indicates an expected call of GetApiGetProjectsByUserID.
func (mr *MockCachingRepositoryMockRecorder) GetApiGetProjectsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiGetProjectsByUserID", reflect.TypeOf((*MockCachingRepository)(nil).GetApiGetProjectsByUserID), ctx, userID)
}

// GetProjectByID mocks base method.
func (m *MockCachingRepository) GetProjectByID(ctx *appcontext.AppContext, id string) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByID", ctx, id)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByID indicates an expected call of GetProjectByID.
func (mr *MockCachingRepositoryMockRecorder) GetProjectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByID", reflect.TypeOf((*MockCachingRepository)(nil).GetProjectByID), ctx, id)
}

// GetProjectCampaignsByProjectID mocks base method.
func (m *MockCachingRepository) GetProjectCampaignsByProjectID(ctx *appcontext.AppContext, id string) ([]domain.ProjectCampaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectCampaignsByProjectID", ctx, id)
	ret0, _ := ret[0].([]domain.ProjectCampaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectCampaignsByProjectID indicates an expected call of GetProjectCampaignsByProjectID.
func (mr *MockCachingRepositoryMockRecorder) GetProjectCampaignsByProjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectCampaignsByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).GetProjectCampaignsByProjectID), ctx, id)
}

// GetProjectCategoriesByProjectID mocks base method.
func (m *MockCachingRepository) GetProjectCategoriesByProjectID(ctx *appcontext.AppContext, id string) ([]domain.ProjectCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectCategoriesByProjectID", ctx, id)
	ret0, _ := ret[0].([]domain.ProjectCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectCategoriesByProjectID indicates an expected call of GetProjectCategoriesByProjectID.
func (mr *MockCachingRepositoryMockRecorder) GetProjectCategoriesByProjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectCategoriesByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).GetProjectCategoriesByProjectID), ctx, id)
}

// GetProjectCollaboratorsByProjectID mocks base method.
func (m *MockCachingRepository) GetProjectCollaboratorsByProjectID(ctx *appcontext.AppContext, id string) ([]domain.ProjectCollaborator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectCollaboratorsByProjectID", ctx, id)
	ret0, _ := ret[0].([]domain.ProjectCollaborator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectCollaboratorsByProjectID indicates an expected call of GetProjectCollaboratorsByProjectID.
func (mr *MockCachingRepositoryMockRecorder) GetProjectCollaboratorsByProjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectCollaboratorsByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).GetProjectCollaboratorsByProjectID), ctx, id)
}

// GetProjectSettingByProjectID mocks base method.
func (m *MockCachingRepository) GetProjectSettingByProjectID(ctx *appcontext.AppContext, id string) (*domain.ProjectSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectSettingByProjectID", ctx, id)
	ret0, _ := ret[0].(*domain.ProjectSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectSettingByProjectID indicates an expected call of GetProjectSettingByProjectID.
func (mr *MockCachingRepositoryMockRecorder) GetProjectSettingByProjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectSettingByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).GetProjectSettingByProjectID), ctx, id)
}

// SetApiGetProjectByID mocks base method.
func (m *MockCachingRepository) SetApiGetProjectByID(ctx *appcontext.AppContext, id, data string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetApiGetProjectByID", ctx, id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetApiGetProjectByID indicates an expected call of SetApiGetProjectByID.
func (mr *MockCachingRepositoryMockRecorder) SetApiGetProjectByID(ctx, id, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetApiGetProjectByID", reflect.TypeOf((*MockCachingRepository)(nil).SetApiGetProjectByID), ctx, id, data)
}

// SetApiGetProjectsByUserID mocks base method.
func (m *MockCachingRepository) SetApiGetProjectsByUserID(ctx *appcontext.AppContext, userID, data string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetApiGetProjectsByUserID", ctx, userID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetApiGetProjectsByUserID indicates an expected call of SetApiGetProjectsByUserID.
func (mr *MockCachingRepositoryMockRecorder) SetApiGetProjectsByUserID(ctx, userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetApiGetProjectsByUserID", reflect.TypeOf((*MockCachingRepository)(nil).SetApiGetProjectsByUserID), ctx, userID, data)
}

// SetProjectByID mocks base method.
func (m *MockCachingRepository) SetProjectByID(ctx *appcontext.AppContext, id string, project domain.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProjectByID", ctx, id, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProjectByID indicates an expected call of SetProjectByID.
func (mr *MockCachingRepositoryMockRecorder) SetProjectByID(ctx, id, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProjectByID", reflect.TypeOf((*MockCachingRepository)(nil).SetProjectByID), ctx, id, project)
}

// SetProjectCampaignsByProjectID mocks base method.
func (m *MockCachingRepository) SetProjectCampaignsByProjectID(ctx *appcontext.AppContext, id string, campaigns []domain.ProjectCampaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProjectCampaignsByProjectID", ctx, id, campaigns)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProjectCampaignsByProjectID indicates an expected call of SetProjectCampaignsByProjectID.
func (mr *MockCachingRepositoryMockRecorder) SetProjectCampaignsByProjectID(ctx, id, campaigns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProjectCampaignsByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).SetProjectCampaignsByProjectID), ctx, id, campaigns)
}

// SetProjectCategoriesByProjectID mocks base method.
func (m *MockCachingRepository) SetProjectCategoriesByProjectID(ctx *appcontext.AppContext, id string, categories []domain.ProjectCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProjectCategoriesByProjectID", ctx, id, categories)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProjectCategoriesByProjectID indicates an expected call of SetProjectCategoriesByProjectID.
func (mr *MockCachingRepositoryMockRecorder) SetProjectCategoriesByProjectID(ctx, id, categories any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProjectCategoriesByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).SetProjectCategoriesByProjectID), ctx, id, categories)
}

// SetProjectCollaboratorsByProjectID mocks base method.
func (m *MockCachingRepository) SetProjectCollaboratorsByProjectID(ctx *appcontext.AppContext, id string, collaborators []domain.ProjectCollaborator) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProjectCollaboratorsByProjectID", ctx, id, collaborators)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProjectCollaboratorsByProjectID indicates an expected call of SetProjectCollaboratorsByProjectID.
func (mr *MockCachingRepositoryMockRecorder) SetProjectCollaboratorsByProjectID(ctx, id, collaborators any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProjectCollaboratorsByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).SetProjectCollaboratorsByProjectID), ctx, id, collaborators)
}

// SetProjectSettingByProjectID mocks base method.
func (m *MockCachingRepository) SetProjectSettingByProjectID(ctx *appcontext.AppContext, id string, setting domain.ProjectSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProjectSettingByProjectID", ctx, id, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProjectSettingByProjectID indicates an expected call of SetProjectSettingByProjectID.
func (mr *MockCachingRepositoryMockRecorder) SetProjectSettingByProjectID(ctx, id, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProjectSettingByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).SetProjectSettingByProjectID), ctx, id, setting)
}
