// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/project/domain/caching.go
//
// Generated by this command:
//
//	mockgen -source=pkg/project/domain/caching.go -destination=internal/mock/project/caching.go -package=mockproject
//

// Package mockproject is a generated GoMock package.
package mockproject

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/project/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockCachingRepository is a mock of CachingRepository interface.
type MockCachingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCachingRepositoryMockRecorder
}

// MockCachingRepositoryMockRecorder is the mock recorder for MockCachingRepository.
type MockCachingRepositoryMockRecorder struct {
	mock *MockCachingRepository
}

// NewMockCachingRepository creates a new mock instance.
func NewMockCachingRepository(ctrl *gomock.Controller) *MockCachingRepository {
	mock := &MockCachingRepository{ctrl: ctrl}
	mock.recorder = &MockCachingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCachingRepository) EXPECT() *MockCachingRepositoryMockRecorder {
	return m.recorder
}

// DeleteProjectByID mocks base method.
func (m *MockCachingRepository) DeleteProjectByID(ctx *appcontext.AppContext, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectByID indicates an expected call of DeleteProjectByID.
func (mr *MockCachingRepositoryMockRecorder) DeleteProjectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectByID", reflect.TypeOf((*MockCachingRepository)(nil).DeleteProjectByID), ctx, id)
}

// DeleteProjectSettingByProjectID mocks base method.
func (m *MockCachingRepository) DeleteProjectSettingByProjectID(ctx *appcontext.AppContext, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProjectSettingByProjectID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProjectSettingByProjectID indicates an expected call of DeleteProjectSettingByProjectID.
func (mr *MockCachingRepositoryMockRecorder) DeleteProjectSettingByProjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProjectSettingByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).DeleteProjectSettingByProjectID), ctx, id)
}

// GetProjectByID mocks base method.
func (m *MockCachingRepository) GetProjectByID(ctx *appcontext.AppContext, id string) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByID", ctx, id)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByID indicates an expected call of GetProjectByID.
func (mr *MockCachingRepositoryMockRecorder) GetProjectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByID", reflect.TypeOf((*MockCachingRepository)(nil).GetProjectByID), ctx, id)
}

// GetProjectSettingByProjectID mocks base method.
func (m *MockCachingRepository) GetProjectSettingByProjectID(ctx *appcontext.AppContext, id string) (*domain.ProjectSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectSettingByProjectID", ctx, id)
	ret0, _ := ret[0].(*domain.ProjectSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectSettingByProjectID indicates an expected call of GetProjectSettingByProjectID.
func (mr *MockCachingRepositoryMockRecorder) GetProjectSettingByProjectID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectSettingByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).GetProjectSettingByProjectID), ctx, id)
}

// SetProjectByID mocks base method.
func (m *MockCachingRepository) SetProjectByID(ctx *appcontext.AppContext, id string, project domain.Project) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProjectByID", ctx, id, project)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProjectByID indicates an expected call of SetProjectByID.
func (mr *MockCachingRepositoryMockRecorder) SetProjectByID(ctx, id, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProjectByID", reflect.TypeOf((*MockCachingRepository)(nil).SetProjectByID), ctx, id, project)
}

// SetProjectSettingByProjectID mocks base method.
func (m *MockCachingRepository) SetProjectSettingByProjectID(ctx *appcontext.AppContext, id string, setting domain.ProjectSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProjectSettingByProjectID", ctx, id, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProjectSettingByProjectID indicates an expected call of SetProjectSettingByProjectID.
func (mr *MockCachingRepositoryMockRecorder) SetProjectSettingByProjectID(ctx, id, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProjectSettingByProjectID", reflect.TypeOf((*MockCachingRepository)(nil).SetProjectSettingByProjectID), ctx, id, setting)
}
