// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/project/domain/project_campaign_category.go
//
// Generated by this command:
//
//	mockgen -source=pkg/project/domain/project_campaign_category.go -destination=internal/mock/project/project_campaign_category.go -package=mockproject
//

// Package mockproject is a generated GoMock package.
package mockproject

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/project/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectCampaignCategoryRepository is a mock of ProjectCampaignCategoryRepository interface.
type MockProjectCampaignCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectCampaignCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectCampaignCategoryRepositoryMockRecorder is the mock recorder for MockProjectCampaignCategoryRepository.
type MockProjectCampaignCategoryRepositoryMockRecorder struct {
	mock *MockProjectCampaignCategoryRepository
}

// NewMockProjectCampaignCategoryRepository creates a new mock instance.
func NewMockProjectCampaignCategoryRepository(ctrl *gomock.Controller) *MockProjectCampaignCategoryRepository {
	mock := &MockProjectCampaignCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockProjectCampaignCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectCampaignCategoryRepository) EXPECT() *MockProjectCampaignCategoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectCampaignCategoryRepository) Create(ctx *appcontext.AppContext, campaignCategory domain.ProjectCampaignCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, campaignCategory)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectCampaignCategoryRepositoryMockRecorder) Create(ctx, campaignCategory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectCampaignCategoryRepository)(nil).Create), ctx, campaignCategory)
}

// Delete mocks base method.
func (m *MockProjectCampaignCategoryRepository) Delete(ctx *appcontext.AppContext, campaignCategory domain.ProjectCampaignCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, campaignCategory)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectCampaignCategoryRepositoryMockRecorder) Delete(ctx, campaignCategory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectCampaignCategoryRepository)(nil).Delete), ctx, campaignCategory)
}

// FindByCampaignID mocks base method.
func (m *MockProjectCampaignCategoryRepository) FindByCampaignID(ctx *appcontext.AppContext, campaignID string) ([]domain.ProjectCampaignCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCampaignID", ctx, campaignID)
	ret0, _ := ret[0].([]domain.ProjectCampaignCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCampaignID indicates an expected call of FindByCampaignID.
func (mr *MockProjectCampaignCategoryRepositoryMockRecorder) FindByCampaignID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCampaignID", reflect.TypeOf((*MockProjectCampaignCategoryRepository)(nil).FindByCampaignID), ctx, campaignID)
}

// FindByID mocks base method.
func (m *MockProjectCampaignCategoryRepository) FindByID(ctx *appcontext.AppContext, campaignCategoryID string) (*domain.ProjectCampaignCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, campaignCategoryID)
	ret0, _ := ret[0].(*domain.ProjectCampaignCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProjectCampaignCategoryRepositoryMockRecorder) FindByID(ctx, campaignCategoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProjectCampaignCategoryRepository)(nil).FindByID), ctx, campaignCategoryID)
}
