// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/project/domain/project_collaborator.go
//
// Generated by this command:
//
//	mockgen -source=pkg/project/domain/project_collaborator.go -destination=internal/mock/project/project_collaborator.go -package=mockproject
//

// Package mockproject is a generated GoMock package.
package mockproject

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/project/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectCollaboratorRepository is a mock of ProjectCollaboratorRepository interface.
type MockProjectCollaboratorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectCollaboratorRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectCollaboratorRepositoryMockRecorder is the mock recorder for MockProjectCollaboratorRepository.
type MockProjectCollaboratorRepositoryMockRecorder struct {
	mock *MockProjectCollaboratorRepository
}

// NewMockProjectCollaboratorRepository creates a new mock instance.
func NewMockProjectCollaboratorRepository(ctrl *gomock.Controller) *MockProjectCollaboratorRepository {
	mock := &MockProjectCollaboratorRepository{ctrl: ctrl}
	mock.recorder = &MockProjectCollaboratorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectCollaboratorRepository) EXPECT() *MockProjectCollaboratorRepositoryMockRecorder {
	return m.recorder
}

// CountTotalByProjectID mocks base method.
func (m *MockProjectCollaboratorRepository) CountTotalByProjectID(ctx *appcontext.AppContext, projectID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotalByProjectID", ctx, projectID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotalByProjectID indicates an expected call of CountTotalByProjectID.
func (mr *MockProjectCollaboratorRepositoryMockRecorder) CountTotalByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotalByProjectID", reflect.TypeOf((*MockProjectCollaboratorRepository)(nil).CountTotalByProjectID), ctx, projectID)
}

// Create mocks base method.
func (m *MockProjectCollaboratorRepository) Create(ctx *appcontext.AppContext, collaborator domain.ProjectCollaborator) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, collaborator)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectCollaboratorRepositoryMockRecorder) Create(ctx, collaborator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectCollaboratorRepository)(nil).Create), ctx, collaborator)
}

// Delete mocks base method.
func (m *MockProjectCollaboratorRepository) Delete(ctx *appcontext.AppContext, collaborator domain.ProjectCollaborator) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, collaborator)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectCollaboratorRepositoryMockRecorder) Delete(ctx, collaborator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectCollaboratorRepository)(nil).Delete), ctx, collaborator)
}

// FindByID mocks base method.
func (m *MockProjectCollaboratorRepository) FindByID(ctx *appcontext.AppContext, collaboratorID string) (*domain.ProjectCollaborator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, collaboratorID)
	ret0, _ := ret[0].(*domain.ProjectCollaborator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProjectCollaboratorRepositoryMockRecorder) FindByID(ctx, collaboratorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProjectCollaboratorRepository)(nil).FindByID), ctx, collaboratorID)
}

// FindByProjectID mocks base method.
func (m *MockProjectCollaboratorRepository) FindByProjectID(ctx *appcontext.AppContext, projectID string) ([]domain.ProjectCollaborator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]domain.ProjectCollaborator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectID indicates an expected call of FindByProjectID.
func (mr *MockProjectCollaboratorRepositoryMockRecorder) FindByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectID", reflect.TypeOf((*MockProjectCollaboratorRepository)(nil).FindByProjectID), ctx, projectID)
}

// Update mocks base method.
func (m *MockProjectCollaboratorRepository) Update(ctx *appcontext.AppContext, collaborator domain.ProjectCollaborator) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, collaborator)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectCollaboratorRepositoryMockRecorder) Update(ctx, collaborator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectCollaboratorRepository)(nil).Update), ctx, collaborator)
}
