// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/project/domain/project_campaign.go
//
// Generated by this command:
//
//	mockgen -source=pkg/project/domain/project_campaign.go -destination=internal/mock/project/project_campaign.go -package=mockproject
//

// Package mockproject is a generated GoMock package.
package mockproject

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/project/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectCampaignRepository is a mock of ProjectCampaignRepository interface.
type MockProjectCampaignRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectCampaignRepositoryMockRecorder
}

// MockProjectCampaignRepositoryMockRecorder is the mock recorder for MockProjectCampaignRepository.
type MockProjectCampaignRepositoryMockRecorder struct {
	mock *MockProjectCampaignRepository
}

// NewMockProjectCampaignRepository creates a new mock instance.
func NewMockProjectCampaignRepository(ctrl *gomock.Controller) *MockProjectCampaignRepository {
	mock := &MockProjectCampaignRepository{ctrl: ctrl}
	mock.recorder = &MockProjectCampaignRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectCampaignRepository) EXPECT() *MockProjectCampaignRepositoryMockRecorder {
	return m.recorder
}

// CountTotalByProjectIDAndCampaignType mocks base method.
func (m *MockProjectCampaignRepository) CountTotalByProjectIDAndCampaignType(ctx *appcontext.AppContext, projectID, campaignType string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotalByProjectIDAndCampaignType", ctx, projectID, campaignType)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotalByProjectIDAndCampaignType indicates an expected call of CountTotalByProjectIDAndCampaignType.
func (mr *MockProjectCampaignRepositoryMockRecorder) CountTotalByProjectIDAndCampaignType(ctx, projectID, campaignType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotalByProjectIDAndCampaignType", reflect.TypeOf((*MockProjectCampaignRepository)(nil).CountTotalByProjectIDAndCampaignType), ctx, projectID, campaignType)
}

// Create mocks base method.
func (m *MockProjectCampaignRepository) Create(ctx *appcontext.AppContext, campaign domain.ProjectCampaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, campaign)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectCampaignRepositoryMockRecorder) Create(ctx, campaign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectCampaignRepository)(nil).Create), ctx, campaign)
}

// FindByID mocks base method.
func (m *MockProjectCampaignRepository) FindByID(ctx *appcontext.AppContext, campaignID string) (*domain.ProjectCampaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, campaignID)
	ret0, _ := ret[0].(*domain.ProjectCampaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProjectCampaignRepositoryMockRecorder) FindByID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProjectCampaignRepository)(nil).FindByID), ctx, campaignID)
}

// FindByProjectID mocks base method.
func (m *MockProjectCampaignRepository) FindByProjectID(ctx *appcontext.AppContext, projectID string) ([]domain.ProjectCampaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]domain.ProjectCampaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectID indicates an expected call of FindByProjectID.
func (mr *MockProjectCampaignRepositoryMockRecorder) FindByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectID", reflect.TypeOf((*MockProjectCampaignRepository)(nil).FindByProjectID), ctx, projectID)
}

// Update mocks base method.
func (m *MockProjectCampaignRepository) Update(ctx *appcontext.AppContext, campaign domain.ProjectCampaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, campaign)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectCampaignRepositoryMockRecorder) Update(ctx, campaign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectCampaignRepository)(nil).Update), ctx, campaign)
}

// MockProjectCampaignHub is a mock of ProjectCampaignHub interface.
type MockProjectCampaignHub struct {
	ctrl     *gomock.Controller
	recorder *MockProjectCampaignHubMockRecorder
}

// MockProjectCampaignHubMockRecorder is the mock recorder for MockProjectCampaignHub.
type MockProjectCampaignHubMockRecorder struct {
	mock *MockProjectCampaignHub
}

// NewMockProjectCampaignHub creates a new mock instance.
func NewMockProjectCampaignHub(ctrl *gomock.Controller) *MockProjectCampaignHub {
	mock := &MockProjectCampaignHub{ctrl: ctrl}
	mock.recorder = &MockProjectCampaignHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectCampaignHub) EXPECT() *MockProjectCampaignHubMockRecorder {
	return m.recorder
}

// FindProjectCampaignByID mocks base method.
func (m *MockProjectCampaignHub) FindProjectCampaignByID(ctx *appcontext.AppContext, id string) (*domain.ProjectCampaignHubData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProjectCampaignByID", ctx, id)
	ret0, _ := ret[0].(*domain.ProjectCampaignHubData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProjectCampaignByID indicates an expected call of FindProjectCampaignByID.
func (mr *MockProjectCampaignHubMockRecorder) FindProjectCampaignByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProjectCampaignByID", reflect.TypeOf((*MockProjectCampaignHub)(nil).FindProjectCampaignByID), ctx, id)
}
