// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/project/domain/project_setting.go
//
// Generated by this command:
//
//	mockgen -source=pkg/project/domain/project_setting.go -destination=internal/mock/project/project_setting.go -package=mockproject
//

// Package mockproject is a generated GoMock package.
package mockproject

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/project/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectSettingRepository is a mock of ProjectSettingRepository interface.
type MockProjectSettingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectSettingRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectSettingRepositoryMockRecorder is the mock recorder for MockProjectSettingRepository.
type MockProjectSettingRepositoryMockRecorder struct {
	mock *MockProjectSettingRepository
}

// NewMockProjectSettingRepository creates a new mock instance.
func NewMockProjectSettingRepository(ctrl *gomock.Controller) *MockProjectSettingRepository {
	mock := &MockProjectSettingRepository{ctrl: ctrl}
	mock.recorder = &MockProjectSettingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectSettingRepository) EXPECT() *MockProjectSettingRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectSettingRepository) Create(ctx *appcontext.AppContext, setting domain.ProjectSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectSettingRepositoryMockRecorder) Create(ctx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectSettingRepository)(nil).Create), ctx, setting)
}

// FindByProjectID mocks base method.
func (m *MockProjectSettingRepository) FindByProjectID(ctx *appcontext.AppContext, projectID string) (*domain.ProjectSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectID", ctx, projectID)
	ret0, _ := ret[0].(*domain.ProjectSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectID indicates an expected call of FindByProjectID.
func (mr *MockProjectSettingRepositoryMockRecorder) FindByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectID", reflect.TypeOf((*MockProjectSettingRepository)(nil).FindByProjectID), ctx, projectID)
}

// Update mocks base method.
func (m *MockProjectSettingRepository) Update(ctx *appcontext.AppContext, setting domain.ProjectSetting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectSettingRepositoryMockRecorder) Update(ctx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectSettingRepository)(nil).Update), ctx, setting)
}
