// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/project/domain/project_invitation.go
//
// Generated by this command:
//
//	mockgen -source=pkg/project/domain/project_invitation.go -destination=internal/mock/project/project_invitation.go -package=mockproject
//

// Package mockproject is a generated GoMock package.
package mockproject

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/project/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectInvitationRepository is a mock of ProjectInvitationRepository interface.
type MockProjectInvitationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectInvitationRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectInvitationRepositoryMockRecorder is the mock recorder for MockProjectInvitationRepository.
type MockProjectInvitationRepositoryMockRecorder struct {
	mock *MockProjectInvitationRepository
}

// NewMockProjectInvitationRepository creates a new mock instance.
func NewMockProjectInvitationRepository(ctrl *gomock.Controller) *MockProjectInvitationRepository {
	mock := &MockProjectInvitationRepository{ctrl: ctrl}
	mock.recorder = &MockProjectInvitationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectInvitationRepository) EXPECT() *MockProjectInvitationRepositoryMockRecorder {
	return m.recorder
}

// CleanupStale mocks base method.
func (m *MockProjectInvitationRepository) CleanupStale(ctx *appcontext.AppContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupStale", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupStale indicates an expected call of CleanupStale.
func (mr *MockProjectInvitationRepositoryMockRecorder) CleanupStale(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupStale", reflect.TypeOf((*MockProjectInvitationRepository)(nil).CleanupStale), ctx)
}

// CountPendingByProjectID mocks base method.
func (m *MockProjectInvitationRepository) CountPendingByProjectID(ctx *appcontext.AppContext, projectID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendingByProjectID", ctx, projectID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendingByProjectID indicates an expected call of CountPendingByProjectID.
func (mr *MockProjectInvitationRepositoryMockRecorder) CountPendingByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendingByProjectID", reflect.TypeOf((*MockProjectInvitationRepository)(nil).CountPendingByProjectID), ctx, projectID)
}

// Create mocks base method.
func (m *MockProjectInvitationRepository) Create(ctx *appcontext.AppContext, invitation domain.ProjectInvitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, invitation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectInvitationRepositoryMockRecorder) Create(ctx, invitation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectInvitationRepository)(nil).Create), ctx, invitation)
}

// Delete mocks base method.
func (m *MockProjectInvitationRepository) Delete(ctx *appcontext.AppContext, invitationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, invitationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectInvitationRepositoryMockRecorder) Delete(ctx, invitationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectInvitationRepository)(nil).Delete), ctx, invitationID)
}

// FindByEmail mocks base method.
func (m *MockProjectInvitationRepository) FindByEmail(ctx *appcontext.AppContext, email string) ([]domain.ProjectInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].([]domain.ProjectInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockProjectInvitationRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockProjectInvitationRepository)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockProjectInvitationRepository) FindByID(ctx *appcontext.AppContext, invitationID string) (*domain.ProjectInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, invitationID)
	ret0, _ := ret[0].(*domain.ProjectInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProjectInvitationRepositoryMockRecorder) FindByID(ctx, invitationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProjectInvitationRepository)(nil).FindByID), ctx, invitationID)
}

// FindByProjectID mocks base method.
func (m *MockProjectInvitationRepository) FindByProjectID(ctx *appcontext.AppContext, projectID string) ([]domain.ProjectInvitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]domain.ProjectInvitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectID indicates an expected call of FindByProjectID.
func (mr *MockProjectInvitationRepositoryMockRecorder) FindByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectID", reflect.TypeOf((*MockProjectInvitationRepository)(nil).FindByProjectID), ctx, projectID)
}

// MarkExpiredInvitations mocks base method.
func (m *MockProjectInvitationRepository) MarkExpiredInvitations(ctx *appcontext.AppContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkExpiredInvitations", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkExpiredInvitations indicates an expected call of MarkExpiredInvitations.
func (mr *MockProjectInvitationRepositoryMockRecorder) MarkExpiredInvitations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkExpiredInvitations", reflect.TypeOf((*MockProjectInvitationRepository)(nil).MarkExpiredInvitations), ctx)
}

// Update mocks base method.
func (m *MockProjectInvitationRepository) Update(ctx *appcontext.AppContext, invitation domain.ProjectInvitation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, invitation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectInvitationRepositoryMockRecorder) Update(ctx, invitation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectInvitationRepository)(nil).Update), ctx, invitation)
}
