// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/project/domain/project_category.go
//
// Generated by this command:
//
//	mockgen -source=pkg/project/domain/project_category.go -destination=internal/mock/project/project_category.go -package=mockproject
//

// Package mockproject is a generated GoMock package.
package mockproject

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/project/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectCategoryRepository is a mock of ProjectCategoryRepository interface.
type MockProjectCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectCategoryRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectCategoryRepositoryMockRecorder is the mock recorder for MockProjectCategoryRepository.
type MockProjectCategoryRepositoryMockRecorder struct {
	mock *MockProjectCategoryRepository
}

// NewMockProjectCategoryRepository creates a new mock instance.
func NewMockProjectCategoryRepository(ctrl *gomock.Controller) *MockProjectCategoryRepository {
	mock := &MockProjectCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockProjectCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectCategoryRepository) EXPECT() *MockProjectCategoryRepositoryMockRecorder {
	return m.recorder
}

// CountTotalByProjectID mocks base method.
func (m *MockProjectCategoryRepository) CountTotalByProjectID(ctx *appcontext.AppContext, projectID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotalByProjectID", ctx, projectID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotalByProjectID indicates an expected call of CountTotalByProjectID.
func (mr *MockProjectCategoryRepositoryMockRecorder) CountTotalByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotalByProjectID", reflect.TypeOf((*MockProjectCategoryRepository)(nil).CountTotalByProjectID), ctx, projectID)
}

// Create mocks base method.
func (m *MockProjectCategoryRepository) Create(ctx *appcontext.AppContext, category domain.ProjectCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProjectCategoryRepositoryMockRecorder) Create(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectCategoryRepository)(nil).Create), ctx, category)
}

// FindByID mocks base method.
func (m *MockProjectCategoryRepository) FindByID(ctx *appcontext.AppContext, categoryID string) (*domain.ProjectCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, categoryID)
	ret0, _ := ret[0].(*domain.ProjectCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProjectCategoryRepositoryMockRecorder) FindByID(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProjectCategoryRepository)(nil).FindByID), ctx, categoryID)
}

// FindByProjectID mocks base method.
func (m *MockProjectCategoryRepository) FindByProjectID(ctx *appcontext.AppContext, projectID string) ([]domain.ProjectCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProjectID", ctx, projectID)
	ret0, _ := ret[0].([]domain.ProjectCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProjectID indicates an expected call of FindByProjectID.
func (mr *MockProjectCategoryRepositoryMockRecorder) FindByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProjectID", reflect.TypeOf((*MockProjectCategoryRepository)(nil).FindByProjectID), ctx, projectID)
}

// Update mocks base method.
func (m *MockProjectCategoryRepository) Update(ctx *appcontext.AppContext, category domain.ProjectCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProjectCategoryRepositoryMockRecorder) Update(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectCategoryRepository)(nil).Update), ctx, category)
}
