// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/project/domain/queue.go
//
// Generated by this command:
//
//	mockgen -source=pkg/project/domain/queue.go -destination=internal/mock/project/queue.go -package=mockproject
//

// Package mockproject is a generated GoMock package.
package mockproject

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/project/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueRepository is a mock of QueueRepository interface.
type MockQueueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueueRepositoryMockRecorder
	isgomock struct{}
}

// MockQueueRepositoryMockRecorder is the mock recorder for MockQueueRepository.
type MockQueueRepositoryMockRecorder struct {
	mock *MockQueueRepository
}

// NewMockQueueRepository creates a new mock instance.
func NewMockQueueRepository(ctrl *gomock.Controller) *MockQueueRepository {
	mock := &MockQueueRepository{ctrl: ctrl}
	mock.recorder = &MockQueueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueRepository) EXPECT() *MockQueueRepositoryMockRecorder {
	return m.recorder
}

// OnFeedbackCreated mocks base method.
func (m *MockQueueRepository) OnFeedbackCreated(ctx *appcontext.AppContext, payload domain.QueueOnFeedbackCreatedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnFeedbackCreated", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnFeedbackCreated indicates an expected call of OnFeedbackCreated.
func (mr *MockQueueRepositoryMockRecorder) OnFeedbackCreated(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnFeedbackCreated", reflect.TypeOf((*MockQueueRepository)(nil).OnFeedbackCreated), ctx, payload)
}
