// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/project/domain/service.go
//
// Generated by this command:
//
//	mockgen -source=pkg/project/domain/service.go -destination=internal/mock/project/service.go -package=mockproject
//

// Package mockproject is a generated GoMock package.
package mockproject

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/project/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetProjectByID mocks base method.
func (m *MockService) GetProjectByID(ctx *appcontext.AppContext, id string) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByID", ctx, id)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByID indicates an expected call of GetProjectByID.
func (mr *MockServiceMockRecorder) GetProjectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByID", reflect.TypeOf((*MockService)(nil).GetProjectByID), ctx, id)
}

// GetProjectSettingByID mocks base method.
func (m *MockService) GetProjectSettingByID(ctx *appcontext.AppContext, projectID string) (*domain.ProjectSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectSettingByID", ctx, projectID)
	ret0, _ := ret[0].(*domain.ProjectSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectSettingByID indicates an expected call of GetProjectSettingByID.
func (mr *MockServiceMockRecorder) GetProjectSettingByID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectSettingByID", reflect.TypeOf((*MockService)(nil).GetProjectSettingByID), ctx, projectID)
}
