// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/project/domain/service.go
//
// Generated by this command:
//
//	mockgen -source=pkg/project/domain/service.go -destination=internal/mock/project/service.go -package=mockproject
//

// Package mockproject is a generated GoMock package.
package mockproject

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/project/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetProjectByID mocks base method.
func (m *MockService) GetProjectByID(ctx *appcontext.AppContext, id string) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByID", ctx, id)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByID indicates an expected call of GetProjectByID.
func (mr *MockServiceMockRecorder) GetProjectByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByID", reflect.TypeOf((*MockService)(nil).GetProjectByID), ctx, id)
}

// GetProjectCampaign mocks base method.
func (m *MockService) GetProjectCampaign(ctx *appcontext.AppContext, projectID, campaignID, userID string) (*domain.ProjectCampaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectCampaign", ctx, projectID, campaignID, userID)
	ret0, _ := ret[0].(*domain.ProjectCampaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectCampaign indicates an expected call of GetProjectCampaign.
func (mr *MockServiceMockRecorder) GetProjectCampaign(ctx, projectID, campaignID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectCampaign", reflect.TypeOf((*MockService)(nil).GetProjectCampaign), ctx, projectID, campaignID, userID)
}

// GetProjectCategoriesByProjectID mocks base method.
func (m *MockService) GetProjectCategoriesByProjectID(ctx *appcontext.AppContext, projectID string, status domain.Status) ([]domain.ProjectCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectCategoriesByProjectID", ctx, projectID, status)
	ret0, _ := ret[0].([]domain.ProjectCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectCategoriesByProjectID indicates an expected call of GetProjectCategoriesByProjectID.
func (mr *MockServiceMockRecorder) GetProjectCategoriesByProjectID(ctx, projectID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectCategoriesByProjectID", reflect.TypeOf((*MockService)(nil).GetProjectCategoriesByProjectID), ctx, projectID, status)
}

// GetProjectCategory mocks base method.
func (m *MockService) GetProjectCategory(ctx *appcontext.AppContext, projectID, categoryID, userID string) (*domain.ProjectCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectCategory", ctx, projectID, categoryID, userID)
	ret0, _ := ret[0].(*domain.ProjectCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectCategory indicates an expected call of GetProjectCategory.
func (mr *MockServiceMockRecorder) GetProjectCategory(ctx, projectID, categoryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectCategory", reflect.TypeOf((*MockService)(nil).GetProjectCategory), ctx, projectID, categoryID, userID)
}

// GetProjectSettingByProjectID mocks base method.
func (m *MockService) GetProjectSettingByProjectID(ctx *appcontext.AppContext, projectID string) (*domain.ProjectSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectSettingByProjectID", ctx, projectID)
	ret0, _ := ret[0].(*domain.ProjectSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectSettingByProjectID indicates an expected call of GetProjectSettingByProjectID.
func (mr *MockServiceMockRecorder) GetProjectSettingByProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectSettingByProjectID", reflect.TypeOf((*MockService)(nil).GetProjectSettingByProjectID), ctx, projectID)
}
