// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: notificationpb/hub.proto

package notificationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_CreateNewFeedbackNotificationDocument_FullMethodName = "/notificationpb.NotificationService/CreateNewFeedbackNotificationDocument"
	NotificationService_CreateNotificationReminder_FullMethodName            = "/notificationpb.NotificationService/CreateNotificationReminder"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	CreateNewFeedbackNotificationDocument(ctx context.Context, in *CreateNewFeedbackNotificationDocumentRequest, opts ...grpc.CallOption) (*CreateNewFeedbackNotificationDocumentResponse, error)
	CreateNotificationReminder(ctx context.Context, in *CreateNotificationReminderRequest, opts ...grpc.CallOption) (*CreateNotificationReminderResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) CreateNewFeedbackNotificationDocument(ctx context.Context, in *CreateNewFeedbackNotificationDocumentRequest, opts ...grpc.CallOption) (*CreateNewFeedbackNotificationDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNewFeedbackNotificationDocumentResponse)
	err := c.cc.Invoke(ctx, NotificationService_CreateNewFeedbackNotificationDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateNotificationReminder(ctx context.Context, in *CreateNotificationReminderRequest, opts ...grpc.CallOption) (*CreateNotificationReminderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNotificationReminderResponse)
	err := c.cc.Invoke(ctx, NotificationService_CreateNotificationReminder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations should embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	CreateNewFeedbackNotificationDocument(context.Context, *CreateNewFeedbackNotificationDocumentRequest) (*CreateNewFeedbackNotificationDocumentResponse, error)
	CreateNotificationReminder(context.Context, *CreateNotificationReminderRequest) (*CreateNotificationReminderResponse, error)
}

// UnimplementedNotificationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) CreateNewFeedbackNotificationDocument(context.Context, *CreateNewFeedbackNotificationDocumentRequest) (*CreateNewFeedbackNotificationDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewFeedbackNotificationDocument not implemented")
}
func (UnimplementedNotificationServiceServer) CreateNotificationReminder(context.Context, *CreateNotificationReminderRequest) (*CreateNotificationReminderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotificationReminder not implemented")
}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_CreateNewFeedbackNotificationDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewFeedbackNotificationDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNewFeedbackNotificationDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNewFeedbackNotificationDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNewFeedbackNotificationDocument(ctx, req.(*CreateNewFeedbackNotificationDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateNotificationReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateNotificationReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_CreateNotificationReminder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateNotificationReminder(ctx, req.(*CreateNotificationReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notificationpb.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewFeedbackNotificationDocument",
			Handler:    _NotificationService_CreateNewFeedbackNotificationDocument_Handler,
		},
		{
			MethodName: "CreateNotificationReminder",
			Handler:    _NotificationService_CreateNotificationReminder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notificationpb/hub.proto",
}
