// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/feedback/domain/billing.go
//
// Generated by this command:
//
//	mockgen -source=pkg/feedback/domain/billing.go -destination=internal/mock/feedback/billing.go -package=mockfeedback
//

// Package mockfeedback is a generated GoMock package.
package mockfeedback

import (
	reflect "reflect"

	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockBillingHub is a mock of BillingHub interface.
type MockBillingHub struct {
	ctrl     *gomock.Controller
	recorder *MockBillingHubMockRecorder
	isgomock struct{}
}

// MockBillingHubMockRecorder is the mock recorder for MockBillingHub.
type MockBillingHubMockRecorder struct {
	mock *MockBillingHub
}

// NewMockBillingHub creates a new mock instance.
func NewMockBillingHub(ctrl *gomock.Controller) *MockBillingHub {
	mock := &MockBillingHub{ctrl: ctrl}
	mock.recorder = &MockBillingHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingHub) EXPECT() *MockBillingHubMockRecorder {
	return m.recorder
}

// CanAcceptFeedback mocks base method.
func (m *MockBillingHub) CanAcceptFeedback(ctx *appcontext.AppContext, projectID string, totalCreatedFeedbacks int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanAcceptFeedback", ctx, projectID, totalCreatedFeedbacks)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanAcceptFeedback indicates an expected call of CanAcceptFeedback.
func (mr *MockBillingHubMockRecorder) CanAcceptFeedback(ctx, projectID, totalCreatedFeedbacks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanAcceptFeedback", reflect.TypeOf((*MockBillingHub)(nil).CanAcceptFeedback), ctx, projectID, totalCreatedFeedbacks)
}
