// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/feedback/domain/caching.go
//
// Generated by this command:
//
//	mockgen -source=pkg/feedback/domain/caching.go -destination=internal/mock/feedback/caching.go -package=mockfeedback
//

// Package mockfeedback is a generated GoMock package.
package mockfeedback

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/feedback/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockCachingRepository is a mock of CachingRepository interface.
type MockCachingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCachingRepositoryMockRecorder
	isgomock struct{}
}

// MockCachingRepositoryMockRecorder is the mock recorder for MockCachingRepository.
type MockCachingRepositoryMockRecorder struct {
	mock *MockCachingRepository
}

// NewMockCachingRepository creates a new mock instance.
func NewMockCachingRepository(ctrl *gomock.Controller) *MockCachingRepository {
	mock := &MockCachingRepository{ctrl: ctrl}
	mock.recorder = &MockCachingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCachingRepository) EXPECT() *MockCachingRepositoryMockRecorder {
	return m.recorder
}

// DeleteFeedbackByID mocks base method.
func (m *MockCachingRepository) DeleteFeedbackByID(ctx *appcontext.AppContext, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFeedbackByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFeedbackByID indicates an expected call of DeleteFeedbackByID.
func (mr *MockCachingRepositoryMockRecorder) DeleteFeedbackByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFeedbackByID", reflect.TypeOf((*MockCachingRepository)(nil).DeleteFeedbackByID), ctx, id)
}

// GetFeedbackByID mocks base method.
func (m *MockCachingRepository) GetFeedbackByID(ctx *appcontext.AppContext, id string) (*domain.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeedbackByID", ctx, id)
	ret0, _ := ret[0].(*domain.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeedbackByID indicates an expected call of GetFeedbackByID.
func (mr *MockCachingRepositoryMockRecorder) GetFeedbackByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeedbackByID", reflect.TypeOf((*MockCachingRepository)(nil).GetFeedbackByID), ctx, id)
}

// GetIpLocationData mocks base method.
func (m *MockCachingRepository) GetIpLocationData(ctx *appcontext.AppContext, ip string) (*domain.IpLocationData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIpLocationData", ctx, ip)
	ret0, _ := ret[0].(*domain.IpLocationData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIpLocationData indicates an expected call of GetIpLocationData.
func (mr *MockCachingRepositoryMockRecorder) GetIpLocationData(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIpLocationData", reflect.TypeOf((*MockCachingRepository)(nil).GetIpLocationData), ctx, ip)
}

// SetFeedbackByID mocks base method.
func (m *MockCachingRepository) SetFeedbackByID(ctx *appcontext.AppContext, id string, feedback domain.Feedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFeedbackByID", ctx, id, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFeedbackByID indicates an expected call of SetFeedbackByID.
func (mr *MockCachingRepositoryMockRecorder) SetFeedbackByID(ctx, id, feedback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFeedbackByID", reflect.TypeOf((*MockCachingRepository)(nil).SetFeedbackByID), ctx, id, feedback)
}

// SetIpLocationData mocks base method.
func (m *MockCachingRepository) SetIpLocationData(ctx *appcontext.AppContext, ip string, data domain.IpLocationData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIpLocationData", ctx, ip, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIpLocationData indicates an expected call of SetIpLocationData.
func (mr *MockCachingRepositoryMockRecorder) SetIpLocationData(ctx, ip, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIpLocationData", reflect.TypeOf((*MockCachingRepository)(nil).SetIpLocationData), ctx, ip, data)
}
