// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/feedback/domain/externalapi.go
//
// Generated by this command:
//
//	mockgen -source=pkg/feedback/domain/externalapi.go -destination=internal/mock/feedback/externalapi.go -package=mockfeedback
//

// Package mockfeedback is a generated GoMock package.
package mockfeedback

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/feedback/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockExternalAPIRepository is a mock of ExternalAPIRepository interface.
type MockExternalAPIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExternalAPIRepositoryMockRecorder
}

// MockExternalAPIRepositoryMockRecorder is the mock recorder for MockExternalAPIRepository.
type MockExternalAPIRepositoryMockRecorder struct {
	mock *MockExternalAPIRepository
}

// NewMockExternalAPIRepository creates a new mock instance.
func NewMockExternalAPIRepository(ctrl *gomock.Controller) *MockExternalAPIRepository {
	mock := &MockExternalAPIRepository{ctrl: ctrl}
	mock.recorder = &MockExternalAPIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalAPIRepository) EXPECT() *MockExternalAPIRepositoryMockRecorder {
	return m.recorder
}

// GetIpLocationData mocks base method.
func (m *MockExternalAPIRepository) GetIpLocationData(ctx *appcontext.AppContext, ip string) (*domain.IpLocationData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIpLocationData", ctx, ip)
	ret0, _ := ret[0].(*domain.IpLocationData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIpLocationData indicates an expected call of GetIpLocationData.
func (mr *MockExternalAPIRepositoryMockRecorder) GetIpLocationData(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIpLocationData", reflect.TypeOf((*MockExternalAPIRepository)(nil).GetIpLocationData), ctx, ip)
}
