// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/feedback/domain/feedback_state_history.go
//
// Generated by this command:
//
//	mockgen -source=pkg/feedback/domain/feedback_state_history.go -destination=internal/mock/feedback/feedback_state_history.go -package=mockfeedback
//

// Package mockfeedback is a generated GoMock package.
package mockfeedback

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/feedback/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedbackStateHistoryRepository is a mock of FeedbackStateHistoryRepository interface.
type MockFeedbackStateHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackStateHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockFeedbackStateHistoryRepositoryMockRecorder is the mock recorder for MockFeedbackStateHistoryRepository.
type MockFeedbackStateHistoryRepositoryMockRecorder struct {
	mock *MockFeedbackStateHistoryRepository
}

// NewMockFeedbackStateHistoryRepository creates a new mock instance.
func NewMockFeedbackStateHistoryRepository(ctrl *gomock.Controller) *MockFeedbackStateHistoryRepository {
	mock := &MockFeedbackStateHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockFeedbackStateHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackStateHistoryRepository) EXPECT() *MockFeedbackStateHistoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFeedbackStateHistoryRepository) Create(ctx *appcontext.AppContext, history domain.FeedbackStateHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFeedbackStateHistoryRepositoryMockRecorder) Create(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeedbackStateHistoryRepository)(nil).Create), ctx, history)
}

// FindWithFilter mocks base method.
func (m *MockFeedbackStateHistoryRepository) FindWithFilter(ctx *appcontext.AppContext, filter domain.FeedbackStateHistoryFilter) ([]domain.FeedbackStateHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithFilter", ctx, filter)
	ret0, _ := ret[0].([]domain.FeedbackStateHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithFilter indicates an expected call of FindWithFilter.
func (mr *MockFeedbackStateHistoryRepositoryMockRecorder) FindWithFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithFilter", reflect.TypeOf((*MockFeedbackStateHistoryRepository)(nil).FindWithFilter), ctx, filter)
}
