// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/feedback/domain/feedback.go
//
// Generated by this command:
//
//	mockgen -source=pkg/feedback/domain/feedback.go -destination=internal/mock/feedback/feedback.go -package=mockfeedback
//

// Package mockfeedback is a generated GoMock package.
package mockfeedback

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/feedback/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedbackRepository is a mock of FeedbackRepository interface.
type MockFeedbackRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackRepositoryMockRecorder
}

// MockFeedbackRepositoryMockRecorder is the mock recorder for MockFeedbackRepository.
type MockFeedbackRepositoryMockRecorder struct {
	mock *MockFeedbackRepository
}

// NewMockFeedbackRepository creates a new mock instance.
func NewMockFeedbackRepository(ctrl *gomock.Controller) *MockFeedbackRepository {
	mock := &MockFeedbackRepository{ctrl: ctrl}
	mock.recorder = &MockFeedbackRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackRepository) EXPECT() *MockFeedbackRepositoryMockRecorder {
	return m.recorder
}

// CountMonthlyUsageForProject mocks base method.
func (m *MockFeedbackRepository) CountMonthlyUsageForProject(ctx *appcontext.AppContext, projectID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMonthlyUsageForProject", ctx, projectID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMonthlyUsageForProject indicates an expected call of CountMonthlyUsageForProject.
func (mr *MockFeedbackRepositoryMockRecorder) CountMonthlyUsageForProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMonthlyUsageForProject", reflect.TypeOf((*MockFeedbackRepository)(nil).CountMonthlyUsageForProject), ctx, projectID)
}

// CountProjectTotalCreatedTodayByIp mocks base method.
func (m *MockFeedbackRepository) CountProjectTotalCreatedTodayByIp(ctx *appcontext.AppContext, projectID, ip string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProjectTotalCreatedTodayByIp", ctx, projectID, ip)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProjectTotalCreatedTodayByIp indicates an expected call of CountProjectTotalCreatedTodayByIp.
func (mr *MockFeedbackRepositoryMockRecorder) CountProjectTotalCreatedTodayByIp(ctx, projectID, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProjectTotalCreatedTodayByIp", reflect.TypeOf((*MockFeedbackRepository)(nil).CountProjectTotalCreatedTodayByIp), ctx, projectID, ip)
}

// Create mocks base method.
func (m *MockFeedbackRepository) Create(ctx *appcontext.AppContext, feedback domain.Feedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFeedbackRepositoryMockRecorder) Create(ctx, feedback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeedbackRepository)(nil).Create), ctx, feedback)
}

// FindWithFilter mocks base method.
func (m *MockFeedbackRepository) FindWithFilter(ctx *appcontext.AppContext, filter domain.FeedbackFilter) ([]domain.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithFilter", ctx, filter)
	ret0, _ := ret[0].([]domain.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithFilter indicates an expected call of FindWithFilter.
func (mr *MockFeedbackRepositoryMockRecorder) FindWithFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithFilter", reflect.TypeOf((*MockFeedbackRepository)(nil).FindWithFilter), ctx, filter)
}

// Update mocks base method.
func (m *MockFeedbackRepository) Update(ctx *appcontext.AppContext, feedback domain.Feedback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, feedback)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFeedbackRepositoryMockRecorder) Update(ctx, feedback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFeedbackRepository)(nil).Update), ctx, feedback)
}
