// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/feedback/domain/feedback_reply.go
//
// Generated by this command:
//
//	mockgen -source=pkg/feedback/domain/feedback_reply.go -destination=internal/mock/feedback/feedback_reply.go -package=mockfeedback
//

// Package mockfeedback is a generated GoMock package.
package mockfeedback

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/feedback/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockFeedbackReplyRepository is a mock of FeedbackReplyRepository interface.
type MockFeedbackReplyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackReplyRepositoryMockRecorder
}

// MockFeedbackReplyRepositoryMockRecorder is the mock recorder for MockFeedbackReplyRepository.
type MockFeedbackReplyRepositoryMockRecorder struct {
	mock *MockFeedbackReplyRepository
}

// NewMockFeedbackReplyRepository creates a new mock instance.
func NewMockFeedbackReplyRepository(ctrl *gomock.Controller) *MockFeedbackReplyRepository {
	mock := &MockFeedbackReplyRepository{ctrl: ctrl}
	mock.recorder = &MockFeedbackReplyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackReplyRepository) EXPECT() *MockFeedbackReplyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFeedbackReplyRepository) Create(ctx *appcontext.AppContext, reply domain.FeedbackReply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reply)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFeedbackReplyRepositoryMockRecorder) Create(ctx, reply any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeedbackReplyRepository)(nil).Create), ctx, reply)
}

// Delete mocks base method.
func (m *MockFeedbackReplyRepository) Delete(ctx *appcontext.AppContext, reply domain.FeedbackReply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, reply)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFeedbackReplyRepositoryMockRecorder) Delete(ctx, reply any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFeedbackReplyRepository)(nil).Delete), ctx, reply)
}

// FindByID mocks base method.
func (m *MockFeedbackReplyRepository) FindByID(ctx *appcontext.AppContext, replyID string) (*domain.FeedbackReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, replyID)
	ret0, _ := ret[0].(*domain.FeedbackReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFeedbackReplyRepositoryMockRecorder) FindByID(ctx, replyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFeedbackReplyRepository)(nil).FindByID), ctx, replyID)
}

// FindWithFilter mocks base method.
func (m *MockFeedbackReplyRepository) FindWithFilter(ctx *appcontext.AppContext, filter domain.FeedbackReplyFilter) ([]domain.FeedbackReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithFilter", ctx, filter)
	ret0, _ := ret[0].([]domain.FeedbackReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithFilter indicates an expected call of FindWithFilter.
func (mr *MockFeedbackReplyRepositoryMockRecorder) FindWithFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithFilter", reflect.TypeOf((*MockFeedbackReplyRepository)(nil).FindWithFilter), ctx, filter)
}

// Update mocks base method.
func (m *MockFeedbackReplyRepository) Update(ctx *appcontext.AppContext, reply domain.FeedbackReply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, reply)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFeedbackReplyRepositoryMockRecorder) Update(ctx, reply any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFeedbackReplyRepository)(nil).Update), ctx, reply)
}
