// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/feedback/domain/iam.go
//
// Generated by this command:
//
//	mockgen -source=pkg/feedback/domain/iam.go -destination=internal/mock/feedback/iam.go -package=mockfeedback
//

// Package mockfeedback is a generated GoMock package.
package mockfeedback

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/feedback/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockIAMHub is a mock of IAMHub interface.
type MockIAMHub struct {
	ctrl     *gomock.Controller
	recorder *MockIAMHubMockRecorder
	isgomock struct{}
}

// MockIAMHubMockRecorder is the mock recorder for MockIAMHub.
type MockIAMHubMockRecorder struct {
	mock *MockIAMHub
}

// NewMockIAMHub creates a new mock instance.
func NewMockIAMHub(ctrl *gomock.Controller) *MockIAMHub {
	mock := &MockIAMHub{ctrl: ctrl}
	mock.recorder = &MockIAMHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAMHub) EXPECT() *MockIAMHubMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockIAMHub) GetUserByID(ctx *appcontext.AppContext, userID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockIAMHubMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockIAMHub)(nil).GetUserByID), ctx, userID)
}
