// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/feedback/domain/notification.go
//
// Generated by this command:
//
//	mockgen -source=pkg/feedback/domain/notification.go -destination=internal/mock/feedback/notification.go -package=mockfeedback
//

// Package mockfeedback is a generated GoMock package.
package mockfeedback

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/feedback/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationHub is a mock of NotificationHub interface.
type MockNotificationHub struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationHubMockRecorder
}

// MockNotificationHubMockRecorder is the mock recorder for MockNotificationHub.
type MockNotificationHubMockRecorder struct {
	mock *MockNotificationHub
}

// NewMockNotificationHub creates a new mock instance.
func NewMockNotificationHub(ctrl *gomock.Controller) *MockNotificationHub {
	mock := &MockNotificationHub{ctrl: ctrl}
	mock.recorder = &MockNotificationHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationHub) EXPECT() *MockNotificationHubMockRecorder {
	return m.recorder
}

// CreateNewFeedbackNotificationDocument mocks base method.
func (m *MockNotificationHub) CreateNewFeedbackNotificationDocument(ctx *appcontext.AppContext, userID string, metadata domain.NotificationMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNewFeedbackNotificationDocument", ctx, userID, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNewFeedbackNotificationDocument indicates an expected call of CreateNewFeedbackNotificationDocument.
func (mr *MockNotificationHubMockRecorder) CreateNewFeedbackNotificationDocument(ctx, userID, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNewFeedbackNotificationDocument", reflect.TypeOf((*MockNotificationHub)(nil).CreateNewFeedbackNotificationDocument), ctx, userID, metadata)
}

// CreateNotificationReminder mocks base method.
func (m *MockNotificationHub) CreateNotificationReminder(ctx *appcontext.AppContext, projectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotificationReminder", ctx, projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNotificationReminder indicates an expected call of CreateNotificationReminder.
func (mr *MockNotificationHubMockRecorder) CreateNotificationReminder(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotificationReminder", reflect.TypeOf((*MockNotificationHub)(nil).CreateNotificationReminder), ctx, projectID)
}
