// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/feedback/domain/project.go
//
// Generated by this command:
//
//	mockgen -source=pkg/feedback/domain/project.go -destination=internal/mock/feedback/project.go -package=mockfeedback
//

// Package mockfeedback is a generated GoMock package.
package mockfeedback

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/feedback/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectHub is a mock of ProjectHub interface.
type MockProjectHub struct {
	ctrl     *gomock.Controller
	recorder *MockProjectHubMockRecorder
	isgomock struct{}
}

// MockProjectHubMockRecorder is the mock recorder for MockProjectHub.
type MockProjectHubMockRecorder struct {
	mock *MockProjectHub
}

// NewMockProjectHub creates a new mock instance.
func NewMockProjectHub(ctrl *gomock.Controller) *MockProjectHub {
	mock := &MockProjectHub{ctrl: ctrl}
	mock.recorder = &MockProjectHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectHub) EXPECT() *MockProjectHubMockRecorder {
	return m.recorder
}

// GetProjectByID mocks base method.
func (m *MockProjectHub) GetProjectByID(ctx *appcontext.AppContext, projectID, userID string) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectByID", ctx, projectID, userID)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectByID indicates an expected call of GetProjectByID.
func (mr *MockProjectHubMockRecorder) GetProjectByID(ctx, projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectByID", reflect.TypeOf((*MockProjectHub)(nil).GetProjectByID), ctx, projectID, userID)
}

// GetProjectCampaignByID mocks base method.
func (m *MockProjectHub) GetProjectCampaignByID(ctx *appcontext.AppContext, campaignID string) (*domain.ProjectCampaignHubData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectCampaignByID", ctx, campaignID)
	ret0, _ := ret[0].(*domain.ProjectCampaignHubData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectCampaignByID indicates an expected call of GetProjectCampaignByID.
func (mr *MockProjectHubMockRecorder) GetProjectCampaignByID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectCampaignByID", reflect.TypeOf((*MockProjectHub)(nil).GetProjectCampaignByID), ctx, campaignID)
}

// GetProjectCampaigns mocks base method.
func (m *MockProjectHub) GetProjectCampaigns(ctx *appcontext.AppContext, projectID string) ([]domain.ProjectCampaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectCampaigns", ctx, projectID)
	ret0, _ := ret[0].([]domain.ProjectCampaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectCampaigns indicates an expected call of GetProjectCampaigns.
func (mr *MockProjectHubMockRecorder) GetProjectCampaigns(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectCampaigns", reflect.TypeOf((*MockProjectHub)(nil).GetProjectCampaigns), ctx, projectID)
}

// GetProjectCategories mocks base method.
func (m *MockProjectHub) GetProjectCategories(ctx *appcontext.AppContext, projectID string) ([]domain.ProjectCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectCategories", ctx, projectID)
	ret0, _ := ret[0].([]domain.ProjectCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectCategories indicates an expected call of GetProjectCategories.
func (mr *MockProjectHubMockRecorder) GetProjectCategories(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectCategories", reflect.TypeOf((*MockProjectHub)(nil).GetProjectCategories), ctx, projectID)
}
