// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/feedback/domain/queue.go
//
// Generated by this command:
//
//	mockgen -source=pkg/feedback/domain/queue.go -destination=internal/mock/feedback/queue.go -package=mockfeedback
//

// Package mockfeedback is a generated GoMock package.
package mockfeedback

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/feedback/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueRepository is a mock of QueueRepository interface.
type MockQueueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueueRepositoryMockRecorder
	isgomock struct{}
}

// MockQueueRepositoryMockRecorder is the mock recorder for MockQueueRepository.
type MockQueueRepositoryMockRecorder struct {
	mock *MockQueueRepository
}

// NewMockQueueRepository creates a new mock instance.
func NewMockQueueRepository(ctrl *gomock.Controller) *MockQueueRepository {
	mock := &MockQueueRepository{ctrl: ctrl}
	mock.recorder = &MockQueueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueRepository) EXPECT() *MockQueueRepositoryMockRecorder {
	return m.recorder
}

// FeedbackCreated mocks base method.
func (m *MockQueueRepository) FeedbackCreated(ctx *appcontext.AppContext, payload domain.QueueFeedbackCreatedPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeedbackCreated", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// FeedbackCreated indicates an expected call of FeedbackCreated.
func (mr *MockQueueRepositoryMockRecorder) FeedbackCreated(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeedbackCreated", reflect.TypeOf((*MockQueueRepository)(nil).FeedbackCreated), ctx, payload)
}
