// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/feedback/domain/service.go
//
// Generated by this command:
//
//	mockgen -source=pkg/feedback/domain/service.go -destination=internal/mock/feedback/service.go -package=mockfeedback
//

// Package mockfeedback is a generated GoMock package.
package mockfeedback

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/feedback/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetIpLocationData mocks base method.
func (m *MockService) GetIpLocationData(ctx *appcontext.AppContext, ip string) (*domain.IpLocationData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIpLocationData", ctx, ip)
	ret0, _ := ret[0].(*domain.IpLocationData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIpLocationData indicates an expected call of GetIpLocationData.
func (mr *MockServiceMockRecorder) GetIpLocationData(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIpLocationData", reflect.TypeOf((*MockService)(nil).GetIpLocationData), ctx, ip)
}
