// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: billingpb/hub.proto

package billingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_CanCreateProject_FullMethodName  = "/billingpb.BillingService/CanCreateProject"
	BillingService_CanAcceptFeedback_FullMethodName = "/billingpb.BillingService/CanAcceptFeedback"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingServiceClient interface {
	CanCreateProject(ctx context.Context, in *CanCreateProjectRequest, opts ...grpc.CallOption) (*CanCreateProjectResponse, error)
	CanAcceptFeedback(ctx context.Context, in *CanAcceptFeedbackRequest, opts ...grpc.CallOption) (*CanAcceptFeedbackResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) CanCreateProject(ctx context.Context, in *CanCreateProjectRequest, opts ...grpc.CallOption) (*CanCreateProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanCreateProjectResponse)
	err := c.cc.Invoke(ctx, BillingService_CanCreateProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CanAcceptFeedback(ctx context.Context, in *CanAcceptFeedbackRequest, opts ...grpc.CallOption) (*CanAcceptFeedbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanAcceptFeedbackResponse)
	err := c.cc.Invoke(ctx, BillingService_CanAcceptFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations should embed UnimplementedBillingServiceServer
// for forward compatibility.
type BillingServiceServer interface {
	CanCreateProject(context.Context, *CanCreateProjectRequest) (*CanCreateProjectResponse, error)
	CanAcceptFeedback(context.Context, *CanAcceptFeedbackRequest) (*CanAcceptFeedbackResponse, error)
}

// UnimplementedBillingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) CanCreateProject(context.Context, *CanCreateProjectRequest) (*CanCreateProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CanCreateProject not implemented")
}
func (UnimplementedBillingServiceServer) CanAcceptFeedback(context.Context, *CanAcceptFeedbackRequest) (*CanAcceptFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CanAcceptFeedback not implemented")
}
func (UnimplementedBillingServiceServer) testEmbeddedByValue() {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call pancis, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_CanCreateProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanCreateProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CanCreateProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CanCreateProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CanCreateProject(ctx, req.(*CanCreateProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CanAcceptFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanAcceptFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CanAcceptFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CanAcceptFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CanAcceptFeedback(ctx, req.(*CanAcceptFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billingpb.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CanCreateProject",
			Handler:    _BillingService_CanCreateProject_Handler,
		},
		{
			MethodName: "CanAcceptFeedback",
			Handler:    _BillingService_CanAcceptFeedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billingpb/hub.proto",
}
