// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/iam/domain/caching.go
//
// Generated by this command:
//
//	mockgen -source=pkg/iam/domain/caching.go -destination=internal/mock/iam/caching.go -package=mockiam
//

// Package mockiam is a generated GoMock package.
package mockiam

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/iam/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockCachingRepository is a mock of CachingRepository interface.
type MockCachingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCachingRepositoryMockRecorder
	isgomock struct{}
}

// MockCachingRepositoryMockRecorder is the mock recorder for MockCachingRepository.
type MockCachingRepositoryMockRecorder struct {
	mock *MockCachingRepository
}

// NewMockCachingRepository creates a new mock instance.
func NewMockCachingRepository(ctrl *gomock.Controller) *MockCachingRepository {
	mock := &MockCachingRepository{ctrl: ctrl}
	mock.recorder = &MockCachingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCachingRepository) EXPECT() *MockCachingRepositoryMockRecorder {
	return m.recorder
}

// DeleteUserByID mocks base method.
func (m *MockCachingRepository) DeleteUserByID(ctx *appcontext.AppContext, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserByID indicates an expected call of DeleteUserByID.
func (mr *MockCachingRepositoryMockRecorder) DeleteUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserByID", reflect.TypeOf((*MockCachingRepository)(nil).DeleteUserByID), ctx, id)
}

// GetUserByID mocks base method.
func (m *MockCachingRepository) GetUserByID(ctx *appcontext.AppContext, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockCachingRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockCachingRepository)(nil).GetUserByID), ctx, id)
}

// SetUserByID mocks base method.
func (m *MockCachingRepository) SetUserByID(ctx *appcontext.AppContext, id string, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserByID", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserByID indicates an expected call of SetUserByID.
func (mr *MockCachingRepositoryMockRecorder) SetUserByID(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserByID", reflect.TypeOf((*MockCachingRepository)(nil).SetUserByID), ctx, id, user)
}
