// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/iam/domain/mailer.go
//
// Generated by this command:
//
//	mockgen -source=pkg/iam/domain/mailer.go -destination=internal/mock/iam/mailer.go -package=mockiam
//

// Package mockiam is a generated GoMock package.
package mockiam

import (
	reflect "reflect"

	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockMailerRepository is a mock of MailerRepository interface.
type MockMailerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMailerRepositoryMockRecorder
	isgomock struct{}
}

// MockMailerRepositoryMockRecorder is the mock recorder for MockMailerRepository.
type MockMailerRepositoryMockRecorder struct {
	mock *MockMailerRepository
}

// NewMockMailerRepository creates a new mock instance.
func NewMockMailerRepository(ctrl *gomock.Controller) *MockMailerRepository {
	mock := &MockMailerRepository{ctrl: ctrl}
	mock.recorder = &MockMailerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailerRepository) EXPECT() *MockMailerRepositoryMockRecorder {
	return m.recorder
}

// SendVerificationCodeEmail mocks base method.
func (m *MockMailerRepository) SendVerificationCodeEmail(ctx *appcontext.AppContext, toEmail, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationCodeEmail", ctx, toEmail, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerificationCodeEmail indicates an expected call of SendVerificationCodeEmail.
func (mr *MockMailerRepositoryMockRecorder) SendVerificationCodeEmail(ctx, toEmail, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationCodeEmail", reflect.TypeOf((*MockMailerRepository)(nil).SendVerificationCodeEmail), ctx, toEmail, code)
}
