// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/iam/domain/queue.go
//
// Generated by this command:
//
//	mockgen -source=pkg/iam/domain/queue.go -destination=internal/mock/iam/queue.go -package=mockiam
//

// Package mockiam is a generated GoMock package.
package mockiam

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/iam/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueRepository is a mock of QueueRepository interface.
type MockQueueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQueueRepositoryMockRecorder
	isgomock struct{}
}

// MockQueueRepositoryMockRecorder is the mock recorder for MockQueueRepository.
type MockQueueRepositoryMockRecorder struct {
	mock *MockQueueRepository
}

// NewMockQueueRepository creates a new mock instance.
func NewMockQueueRepository(ctrl *gomock.Controller) *MockQueueRepository {
	mock := &MockQueueRepository{ctrl: ctrl}
	mock.recorder = &MockQueueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueRepository) EXPECT() *MockQueueRepositoryMockRecorder {
	return m.recorder
}

// SendVerificationCodeEmail mocks base method.
func (m *MockQueueRepository) SendVerificationCodeEmail(ctx *appcontext.AppContext, payload domain.QueueSendVerificationCodeEmailPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationCodeEmail", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerificationCodeEmail indicates an expected call of SendVerificationCodeEmail.
func (mr *MockQueueRepositoryMockRecorder) SendVerificationCodeEmail(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationCodeEmail", reflect.TypeOf((*MockQueueRepository)(nil).SendVerificationCodeEmail), ctx, payload)
}
