// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/iam/domain/verification_code.go
//
// Generated by this command:
//
//	mockgen -source=pkg/iam/domain/verification_code.go -destination=internal/mock/iam/verification_code.go -package=mockiam
//

// Package mockiam is a generated GoMock package.
package mockiam

import (
	reflect "reflect"

	domain "github.com/namhq1989/ezfeedback-api-server/pkg/iam/domain"
	appcontext "github.com/namhq1989/go-utilities/appcontext"
	gomock "go.uber.org/mock/gomock"
)

// MockVerificationCodeRepository is a mock of VerificationCodeRepository interface.
type MockVerificationCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationCodeRepositoryMockRecorder
}

// MockVerificationCodeRepositoryMockRecorder is the mock recorder for MockVerificationCodeRepository.
type MockVerificationCodeRepositoryMockRecorder struct {
	mock *MockVerificationCodeRepository
}

// NewMockVerificationCodeRepository creates a new mock instance.
func NewMockVerificationCodeRepository(ctrl *gomock.Controller) *MockVerificationCodeRepository {
	mock := &MockVerificationCodeRepository{ctrl: ctrl}
	mock.recorder = &MockVerificationCodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationCodeRepository) EXPECT() *MockVerificationCodeRepositoryMockRecorder {
	return m.recorder
}

// CleanupStale mocks base method.
func (m *MockVerificationCodeRepository) CleanupStale(ctx *appcontext.AppContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupStale", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupStale indicates an expected call of CleanupStale.
func (mr *MockVerificationCodeRepositoryMockRecorder) CleanupStale(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupStale", reflect.TypeOf((*MockVerificationCodeRepository)(nil).CleanupStale), ctx)
}

// CountTotalSentTodayByIp mocks base method.
func (m *MockVerificationCodeRepository) CountTotalSentTodayByIp(ctx *appcontext.AppContext, ip string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotalSentTodayByIp", ctx, ip)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotalSentTodayByIp indicates an expected call of CountTotalSentTodayByIp.
func (mr *MockVerificationCodeRepositoryMockRecorder) CountTotalSentTodayByIp(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotalSentTodayByIp", reflect.TypeOf((*MockVerificationCodeRepository)(nil).CountTotalSentTodayByIp), ctx, ip)
}

// Create mocks base method.
func (m *MockVerificationCodeRepository) Create(ctx *appcontext.AppContext, code domain.VerificationCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVerificationCodeRepositoryMockRecorder) Create(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVerificationCodeRepository)(nil).Create), ctx, code)
}

// Find mocks base method.
func (m *MockVerificationCodeRepository) Find(ctx *appcontext.AppContext, ip, email, code string) (*domain.VerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, ip, email, code)
	ret0, _ := ret[0].(*domain.VerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockVerificationCodeRepositoryMockRecorder) Find(ctx, ip, email, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockVerificationCodeRepository)(nil).Find), ctx, ip, email, code)
}

// Update mocks base method.
func (m *MockVerificationCodeRepository) Update(ctx *appcontext.AppContext, code domain.VerificationCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVerificationCodeRepositoryMockRecorder) Update(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVerificationCodeRepository)(nil).Update), ctx, code)
}
